import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import {jsPDF} from 'jspdf';
import {DatabaseSync} from 'node:sqlite';
globalThis.migrationJsPdf=jsPDF;
const cache=new Map();
function mod(name){if(cache.has(name))return cache.get(name);let code=ts.transpileModule(readFileSync(new URL('../app/'+name+'.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
 code=code.replace(/from ["']([^"']+)["']/g,(_,dep)=>{if(dep==='jspdf')return 'from "data:text/javascript,export const jsPDF=globalThis.migrationJsPdf"';if(dep==='cloudflare:workers')return 'from "data:text/javascript,export const env=globalThis.migrationEnv"';if(dep.endsWith('server-auth'))return 'from "data:text/javascript,export const portalActor=async()=>globalThis.migrationActor"';return 'from '+JSON.stringify(mod(path.posix.normalize(path.posix.join(path.posix.dirname(name),dep))));});
 const url='data:text/javascript;base64,'+Buffer.from(code).toString('base64');cache.set(name,url);return url;}
const db=new DatabaseSync(':memory:');
for(const file of ['0011_boring_professor_monster.sql','0012_whole_photon.sql'])db.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));
function prepare(sql){return {bind(...args){return {first:async()=>db.prepare(sql).get(...args),all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>db.prepare(sql).run(...args),_run:()=>db.prepare(sql).run(...args)};}};}
globalThis.migrationEnv={DB:{prepare,async batch(items){db.exec('BEGIN');try{const result=items.map(x=>x._run());db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}}};
const model=await import(mod('epanitia-migration-model')),service=await import(mod('document-service')),route=await import(mod('api/documents/route'));
const actor={id:'test-owner',email:'owner@example.com',name:'PEGAWAI UJIAN',role:'teacher'},users=[{id:'test-owner',name:'PEGAWAI UJIAN'},{id:'test-chair',name:'PENGERUSI UJIAN'}];
const data={panelId:'kurikulum-3-1-1',year:2026,title:'Ujian sahaja',preparedBy:'test-owner',letterDate:'2026-09-10',meetingDate:'2026-09-15',meetingNo:'1',time:'14:00',venue:'RUANG UJIAN',recipients:'Semua ahli panitia',chair:'test-chair',agenda:['Agenda ujian'],reference:'',fileCode:''};
test('registered panel and staff IDs survive the migrated document adapter',()=>{assert.equal(model.registeredPanitia.length,19);assert.doesNotThrow(()=>model.validateBuilder('meeting-call',data,users));const input=model.coreInput('meeting-call',data,users);assert.equal(input.people.chair.id,'test-chair');assert.equal(input.values.chair,'PENGERUSI UJIAN');assert.equal(input.values.letterDate,'2026-09-10');assert.equal(input.values.date,'2026-09-15');assert.throws(()=>model.validateBuilder('meeting-call',{...data,panelId:'Nama manual'},users));assert.throws(()=>model.validateBuilder('meeting-call',{...data,chair:'Nama manual'},users));});
test('OPR letterhead and four core PDFs produce A4 documents without inventing approvals',async()=>{mkdirSync('tmp/pdfs',{recursive:true});for(const [id,extra] of [['meeting-call',{}],['appointment',{recipient:'test-owner',role:'Setiausaha',startDate:'2026-09-16',endDate:'2026-12-31',duties:['Tugas untuk ujian. '.repeat(90)]}],['minutes',{attendance:['test-owner'],matters:[{discussion:'Makluman ujian',decision:'Catatan ujian. '.repeat(140),status:'Makluman sahaja'}]}],['pcg',{requestDate:'2026-09-10',purpose:'Bahan ujian',items:Array.from({length:30},(_,i)=>({id:String(i),item:'Bahan ujian '+i,quantity:2,unitPrice:12.35}))}]] ) {const blob=model.migratedCorePdf(id,{...data,...extra},users);assert.equal(blob.type,'application/pdf');assert.ok(blob.size>10000);writeFileSync('tmp/pdfs/opr-head-'+id+'.pdf',Buffer.from(await blob.arrayBuffer()));}});
test('master mappings use explicit category; unknown types need review',async()=>{for(const [n,type,category,metadata] of [[1,'Surat Panggilan Mesyuarat','03',{}],[2,'Nota Minta PCG','06',{}],[3,'Dokumen sokongan lain','',{}],[4,'Dokumen sokongan lain','04',{epanitiaCategory:'04'}]]){const result=await service.registerDocument(actor,{title:'UJIAN '+n,documentType:type,sourceModule:'e-Panitia',schoolYear:2026,status:'draft',file:{id:'test-file-000'+n,name:'ujian.pdf',viewUrl:'https://example.com/test.pdf'},metadata});assert.equal(db.prepare("SELECT destination_category_id FROM document_mappings WHERE document_id=? AND destination_module='epanitia'").get(result.documentId).destination_category_id,category);}});
test('new draft versions preserve master ID, reject another owner and keep approved pointer',async()=>{const result=await service.registerDocument(actor,{title:'Versi ujian',documentType:'Minit Mesyuarat',sourceModule:'e-Panitia',schoolYear:2026,status:'draft',file:{id:'test-version-base',name:'base.pdf',viewUrl:'https://example.com/base.pdf'}});const file={id:'test-version-next',name:'next.pdf',viewUrl:'https://example.com/next.pdf'};await assert.rejects(service.addDocumentVersion({...actor,id:'other',email:'other@example.com'},result.documentId,file));const next=await service.addDocumentVersion(actor,result.documentId,file);assert.equal(db.prepare('SELECT current_version_id FROM documents WHERE id=?').get(result.documentId).current_version_id,next.versionId);const retry=await service.addDocumentVersion(actor,result.documentId,file);assert.equal(retry.versionId,next.versionId);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM document_versions WHERE document_id=?').get(result.documentId).n,2);await service.approveDocument({...actor,role:'admin'},result.documentId,next.versionId);await service.addDocumentVersion(actor,result.documentId,{...file,id:'test-version-third'});assert.equal(db.prepare('SELECT current_version_id FROM documents WHERE id=?').get(result.documentId).current_version_id,next.versionId);});
test('API refuses approval shortcuts and foreign draft updates',async()=>{globalThis.migrationActor=actor;const req=body=>new Request('https://school.example/api/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let r=await route.POST(req({action:'approve',documentId:'fake',versionId:'fake'}));assert.equal(r.status,403);r=await route.POST(req({action:'save-draft',id:'draft-test',schoolYear:2026,documentType:'Minit',payload:{}}));assert.equal(r.status,200);globalThis.migrationActor={...actor,id:'other',email:'other@example.com'};r=await route.POST(req({action:'save-draft',id:'draft-test',schoolYear:2026,documentType:'Minit',payload:{}}));assert.equal(r.status,403);globalThis.migrationActor=actor;r=await route.POST(req({action:'register',input:{title:'Ujian status',documentType:'Minit',sourceModule:'e-Panitia',schoolYear:2026,status:'approved',file:{id:'test-status-file',name:'file.pdf',viewUrl:'https://example.com/file.pdf'}}}));assert.equal(r.status,200);const record=await r.json();assert.equal(db.prepare('SELECT status FROM documents WHERE id=?').get(record.documentId).status,'draft');r=await route.POST(req({action:'register-link',title:'Ujian',url:'https://user:pass@example.com',schoolYear:2026}));assert.equal(r.status,400);});

test('bulk appointments validate registered recipients and individual roles',()=>{const bulk={...data,allAjk:true,recipients:[{teacher:'test-owner',role:'Setiausaha'}],startDate:'2026-09-16',endDate:'2026-12-31',duties:['Tugas ujian']};assert.doesNotThrow(()=>model.validateBuilder('appointment',bulk,users));assert.throws(()=>model.validateBuilder('appointment',{...bulk,recipients:[]},users));assert.throws(()=>model.validateBuilder('appointment',{...bulk,recipients:[{teacher:'Nama manual',role:'Setiausaha'}]},users));});
