import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import ts from'typescript';
import{normalizeForm6,form6Errors}from'../app/form6-model.ts';import{matchName,normalizeDocumentName}from'../app/name-matching.ts';
const source=readFileSync(new URL('../app/api/form6-timetable/route.ts',import.meta.url),'utf8');
const code=ts.transpileModule(source.replace(/^import .*;\n/gm,'').replace(/export /g,''),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const users=[{id:'u1',name:'MUHAMMAD AZWAN BIN AHMAD'}],teacher={name:'MUHAMAD AZWAN B AHMAD',userId:'',lessons:[{day:'Isnin',start:1,end:2,subject:'SEJ',className:'6 TEST'}]};
function api(saved={}){const calls=[];const DB={prepare(){return {async run(){},async all(){return {results:users};}};}};return {calls,...new Function('env','portalActor','generateAI','normalizeForm6','form6Errors','matchDocumentRows',code+';return {POST};')({DB},async()=>({id:'admin',role:'admin'}),async()=>({text:JSON.stringify({teachers:[teacher]})}),normalizeForm6,form6Errors,async(rows,directory,track)=>{calls.push(track);return rows.map(row=>({...row,...matchName(row.name,directory,saved)}));})};}
function request(asc=true){const form=new FormData();form.set('file',new File([asc?'%PDF-test':new Uint8Array([255,216,255,0])],asc?'test.pdf':'test.jpg'));form.set('kind','teachers');if(asc)form.set('ascData',JSON.stringify({teachers:[teacher],pageCount:1}));return new Request('https://portal/api/form6-timetable',{method:'POST',body:form});}
for(const asc of [true,false])test(`${asc?'aSc':'image extraction'} uses shared fuzzy candidates and preserves lessons`,async()=>{const route=api(),response=await route.POST(request(asc));assert.equal(response.status,200);const {rows}=await response.json();assert.equal(rows[0].userId,'');assert.equal(rows[0].candidates[0].userId,'u1');assert.equal(rows[0].original_name,teacher.name);assert.deepEqual(rows[0].lessons,teacher.lessons);assert.deepEqual(route.calls,[true]);});
test('Form Six upload reuses confirmed mapping before fuzzy suggestions',async()=>{const route=api({[normalizeDocumentName(teacher.name)]:{userId:'u1'}}),response=await route.POST(request());const {rows}=await response.json();assert.equal(rows[0].userId,'u1');assert.equal(rows[0].match_type,'Saved Mapping');});
