import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
import {matchName,normalizeDocumentName,nameSimilarity,defaultThresholds} from '../app/name-matching.ts';
import {documentNameKey} from '../app/staff-work-model.ts';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
const compile=p=>ts.transpileModule(read(p).replace(/^import .*;\n/gm,'').replace(/export /g,''),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
function fixture(){const sql=new DatabaseSync(':memory:');sql.exec("CREATE TABLE portal_users(id TEXT PRIMARY KEY,name TEXT,status TEXT,deleted_at TEXT);INSERT INTO portal_users VALUES('u1','MUHAMMAD AZWAN BIN AHMAD','active',NULL),('u2','MUHAMMAD AZHAR BIN AHMAD','active',NULL);CREATE TABLE staff_name_mappings(name_key TEXT PRIMARY KEY,source_name TEXT,user_id TEXT,updated_by TEXT,updated_at TEXT);");sql.exec(read('drizzle/0016_name_match_memory.sql'));const DB={prepare(query){const s=sql.prepare(query);let args=[];return {bind(...a){args=a;return this;},async all(){return {results:s.all(...args)};},async first(){return s.get(...args)||null;},async run(){return s.run(...args);}};},async batch(stmts){return Promise.all(stmts.map(s=>s.run()));}};const routes=new Function('env','portalActor','normalizeDocumentName','nameSimilarity','documentNameKey','matchDocumentRows',compile('app/api/document-name-mappings/route.ts')+';return {GET,POST};')({DB},async req=>({id:'admin',role:req.headers.get('role')||'admin'}),normalizeDocumentName,nameSimilarity,documentNameKey,async()=>[]);const match=new Function('env','matchName','normalizeDocumentName','defaultThresholds',compile('app/lib/document-name-matching.ts')+';return matchDocumentRows;')({DB},matchName,normalizeDocumentName,defaultThresholds);return {sql,routes,match,post:body=>routes.POST(new Request('https://test',{method:'POST',body:JSON.stringify(body)})),users:sql.prepare('SELECT id,name FROM portal_users').all()};}
test('persistent confirmations survive matching, count reuse, correction and no-match',async()=>{const f=fixture(),name='MUHAMAD AZWAN B AHMAD';assert.equal((await f.match([{name}],f.users,true))[0].userId,'');assert.equal((await f.post({action:'confirm',name,userId:'u1'})).status,200);assert.equal((await f.match([{name}],f.users,true))[0].match_type,'Saved Mapping');assert.equal(f.sql.prepare('SELECT usage_count FROM name_match_mappings').get().usage_count,1);await f.post({action:'confirm',name,userId:'u2'});assert.equal((await f.match([{name}],f.users))[0].userId,'u2');assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM name_match_mappings').get().n,1);await f.post({action:'no_match',name});assert.equal((await f.match([{name}],f.users))[0].match_type,'Confirmed No Match');await f.post({action:'forget',name});assert.equal((await f.match([{name}],f.users))[0].userId,'');});
test('only admins confirm memory; invalid users and thresholds rejected',async()=>{const f=fixture();assert.equal((await f.routes.POST(new Request('https://test',{method:'POST',headers:{role:'user'},body:JSON.stringify({action:'confirm',name:'X',userId:'u1'})}))).status,403);assert.equal((await f.post({action:'confirm',name:'X',userId:'missing'})).status,400);assert.equal((await f.post({action:'settings',high:80,review:90,margin:5})).status,400);assert.equal((await f.post({action:'settings',high:97,review:87,margin:7})).status,200);});
test('legacy human confirmations retain provenance and are not reimported after forgetting',async()=>{const f=fixture(),name='En. Azwan Ahmad';f.sql.prepare('INSERT INTO staff_name_mappings VALUES(?,?,?,?,?)').run(documentNameKey(name),name,'u1','old-admin','2026-09-01');assert.equal((await f.match([{name}],f.users))[0].match_type,'Saved Mapping');assert.equal(f.sql.prepare('SELECT confirmed_by FROM name_match_mappings').get().confirmed_by,'old-admin');await f.post({action:'forget',name});assert.notEqual((await f.match([{name}],f.users))[0].match_type,'Saved Mapping');});
