"use client";
import {useEffect,useMemo,useState} from "react";
import {Archive,ChevronRight,Clock3,ExternalLink,FileText,FolderOpen,Link2,RefreshCw,Upload,Users} from "lucide-react";
const EPANITIA_CATEGORIES = [["01","01 — Pengurusan Am"],["02","02 — Perancangan Strategik"],["03","03 — Mesyuarat"],["04","04 — Kurikulum dan Pentaksiran"],["05","05 — Perancangan dan Program"],["06","06 — Kewangan PCG"],["07","07 — Pembangunan Profesional"],["08","08 — Laporan dan Penilaian"]] as const;

type User={id:string;email:string;name:string;position:string;role:string};
type Row={id:string;title:string;documentType:string;sourceModule:string;status:string;panelId:string;programmeId:string;updatedAt:string;versionId:string;versionNumber:number;driveFileId:string;driveUrl:string;filename:string;destinationModule:string;destinationCategoryId:string;destinationStandardId:string;mappingStatus:string};
const types=["Minit Mesyuarat Panitia","Laporan OPR","Kertas Kerja","Post-mortem Pentaksiran","Carta Organisasi","Nota Minta PCG","Laporan Tahunan","Dokumen sokongan lain"];
const fileBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(",")[1]||"");r.onerror=()=>reject(r.error);r.readAsDataURL(file)});

export function EPanitiaCentre({notify,user}:{notify:(message:string)=>void;user:User|null}){
 const year=new Date().getFullYear(),[rows,setRows]=useState<Row[]>([]),[stats,setStats]=useState<{documents?:number;mappings?:number;pending?:number}>({}),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[category,setCategory]=useState("all"),[selected,setSelected]=useState<Row|null>(null),[uploadOpen,setUploadOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const [form,setForm]=useState({title:"",documentType:types[0],panelId:"",category:"03",mapping:"both",programmeId:""});const [file,setFile]=useState<File|null>(null);
 const load=async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/documents?module=epanitia&year=${year}`,{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error||"Rekod tidak dapat dibaca");setRows(data.documents||[]);setStats(data.stats||{});}catch(reason){setError(reason instanceof Error?reason.message:"Rekod tidak dapat dibaca")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const unique=useMemo(()=>Array.from(new Map(rows.map(row=>[row.id,row])).values()),[rows]);
 const visible=unique.filter(row=>(category==="all"||row.destinationCategoryId===category)&&`${row.title} ${row.documentType} ${row.panelId}`.toLowerCase().includes(search.toLowerCase()));
 const submit=async()=>{if(!file||!form.title.trim())return notify("Pilih fail dan lengkapkan tajuk dokumen");setSaving(true);setError("");try{const base64=await fileBase64(file);const upload=await fetch("/api/drive",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"document-upload",title:form.title,documentType:form.documentType,schoolYear:year,panelId:form.panelId,programmeId:form.programmeId,files:[{name:file.name,mimeType:file.type,base64}]})}),data=await upload.json();if(!upload.ok||!data.document?.documentId)throw new Error(data.error||"Google Drive belum mengesahkan fail");for(const module of form.mapping==="both"?["management","skas"]:form.mapping==="none"?[]:[form.mapping])await fetch("/api/documents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"map",documentId:data.document.documentId,destinationModule:module,mappingStatus:"pending"})});setUploadOpen(false);setFile(null);setForm(current=>({...current,title:""}));notify("Fail disahkan Google Drive dan satu rekod induk telah diwujudkan");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Fail tidak dapat disimpan")}finally{setSaving(false)}};
 const archiveDoc=async(row:Row)=>{const response=await fetch("/api/documents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"archive",documentId:row.id})}),data=await response.json();if(response.status===409)return notify(`Dokumen digunakan oleh ${(data.impact||[]).length} pemetaan. Arkib memerlukan pengesahan pentadbir.`);notify(data.error||"Dokumen diarkibkan")};
 return <div className="epanitia-shell"><header className="epanitia-head"><div><span className="modal-overline">REKOD DOKUMEN BERSAMA</span><h2 id="folder-title">e-Panitia</h2><p>Satu dokumen, satu rekod induk dan satu fail Google Drive sekolah.</p></div><button className="epanitia-upload" onClick={()=>setUploadOpen(true)}><Upload/>Daftar dokumen</button></header>
 <section className="epanitia-kpis"><article><FileText/><span><small>DOKUMEN UNIK</small><strong>{stats.documents||unique.length}</strong></span></article><article><Link2/><span><small>PEMETAAN MODUL</small><strong>{stats.mappings||0}</strong></span></article><article><Clock3/><span><small>MENUNGGU SEMAKAN</small><strong>{stats.pending||0}</strong></span></article><article><FolderOpen/><span><small>STORAN FAIL</small><strong>Google Drive</strong></span></article></section>
 <section className="epanitia-work"><aside><strong>Fail Panitia {year}</strong><button className={category==="all"?"active":""} onClick={()=>setCategory("all")}><FolderOpen/>Semua dokumen <b>{unique.length}</b></button>{EPANITIA_CATEGORIES.map(([id,label])=><button className={category===id?"active":""} key={id} onClick={()=>setCategory(id)}><span>{id}</span>{label.replace(`${id} — `,"")}</button>)}</aside><main><div className="epanitia-toolbar"><label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari tajuk, jenis atau panitia"/></label><button onClick={()=>void load()} aria-label="Segarkan"><RefreshCw/></button></div>{error&&<p className="epanitia-error">{error}</p>}{loading?<p className="epanitia-empty">Membaca rekod dokumen bersama…</p>:visible.length?<div className="epanitia-list">{visible.map(row=><button key={row.id} onClick={()=>setSelected(row)}><FileText/><span><strong>{row.title}</strong><small>{row.documentType} · {row.panelId||"Semua panitia"}</small><em>Dicipta melalui {row.sourceModule} · Versi {row.versionNumber}</em></span><i className={row.status}>{row.status==="approved"?"Diluluskan":"Draf"}</i><ChevronRight/></button>)}</div>:<p className="epanitia-empty">Belum ada dokumen dalam pilihan ini.</p>}</main></section>
 {selected&&<div className="epanitia-detail-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><section><button className="folder-float-close" onClick={()=>setSelected(null)}>×</button><span className="modal-overline">DOKUMEN INDUK</span><h3>{selected.title}</h3><p>{selected.documentType} · {selected.panelId||"Semua panitia"}</p><dl><div><dt>Fail asal</dt><dd>Google Drive Sekolah</dd></div><div><dt>Dicipta melalui</dt><dd>{selected.sourceModule}</dd></div><div><dt>Versi semasa</dt><dd>{selected.versionNumber} · {selected.status}</dd></div><div><dt>ID fail Drive</dt><dd>{selected.driveFileId}</dd></div><div><dt>Digunakan dalam</dt><dd>e-Panitia · pemetaan bersama tersedia</dd></div></dl><div className="epanitia-actions"><a href={selected.driveUrl} target="_blank" rel="noreferrer"><ExternalLink/>Buka fail</a><button onClick={()=>notify("Sejarah versi menggunakan rekod induk yang sama")}><Clock3/>Sejarah versi</button><button onClick={()=>notify("Pemetaan modul dibaca daripada rekod bersama")}><Users/>Lihat pemetaan</button><button onClick={()=>void archiveDoc(selected)}><Archive/>Arkib</button></div></section></div>}
 {uploadOpen&&<div className="epanitia-detail-backdrop" onMouseDown={e=>e.target===e.currentTarget&&!saving&&setUploadOpen(false)}><section className="epanitia-upload-card"><button className="folder-float-close" onClick={()=>setUploadOpen(false)}>×</button><span className="modal-overline">DAFTAR SEKALI, GUNA BERSAMA</span><h3>Dokumen e-Panitia</h3><label>Tajuk dokumen<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Jenis dokumen<select value={form.documentType} onChange={e=>setForm({...form,documentType:e.target.value})}>{types.map(type=><option key={type}>{type}</option>)}</select></label><div className="epanitia-form-grid"><label>Panitia / unit<input value={form.panelId} onChange={e=>setForm({...form,panelId:e.target.value})} placeholder="Contoh: Sejarah"/></label><label>Folder e-Panitia<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{EPANITIA_CATEGORIES.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label></div><label>Program berkaitan (pilihan)<input value={form.programmeId} onChange={e=>setForm({...form,programmeId:e.target.value})} placeholder="ID program jika tersedia"/></label><label>Pemetaan tambahan<select value={form.mapping} onChange={e=>setForm({...form,mapping:e.target.value})}><option value="none">Simpan dalam e-Panitia sahaja</option><option value="management">Peta juga ke Pengurusan Sekolah</option><option value="skas">Peta juga ke SK@S</option><option value="both">Peta ke kedua-duanya</option></select></label><label className="epanitia-file"><input type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png" onChange={e=>setFile(e.target.files?.[0]||null)}/><Upload/><strong>{file?file.name:"Pilih fail"}</strong><small>PDF, Word, Excel atau gambar · maksimum 12 MB</small></label>{error&&<p className="epanitia-error">{error}</p>}<button className="epanitia-save" onClick={()=>void submit()} disabled={saving}>{saving?"Menunggu pengesahan Google Drive…":"Simpan ke Google Drive sekolah"}</button></section></div>}</div>
}
