'use client';
import {useEffect,useState} from 'react';
import {schoolDays,form6Errors,type Form6Data} from './form6-model';
export function Form6Settings(){
 const [data,setData]=useState<Form6Data>({teachers:[],times:[]}),[users,setUsers]=useState<{id:string;name:string}[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[active,setActive]=useState(''),[teacher,setTeacher]=useState(0),[day,setDay]=useState('Isnin'),[reviewed,setReviewed]=useState(false);
 useEffect(()=>{fetch('/api/form6-timetable').then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error);setUsers(b.users);setData(b.versions.find((v:{id:string;data:Form6Data;updatedAt:string})=>v.id==='draft')?.data||b.versions.find((v:{id:string;data:Form6Data;updatedAt:string})=>v.id==='active')?.data||{teachers:[],times:[]});setActive(b.versions.find((v:{id:string;data:Form6Data;updatedAt:string})=>v.id==='active')?.updatedAt||'');}).catch(e=>setMessage(e.message));},[]);
 const change=(next:Form6Data)=>{setData(next);setReviewed(false);};
 async function upload(file:File|undefined,kind:string){if(!file)return;setBusy(true);setMessage('Membaca dokumen. Jadual aktif masih digunakan.');try{const form=new FormData();form.append('file',file);form.append('kind',kind);const r=await fetch('/api/form6-timetable',{method:'POST',body:form}),b=await r.json();if(!r.ok)throw Error(b.error);change({...data,[kind]:b.rows});setTeacher(0);setMessage(`${file.name} telah dibaca. Semak semua guru, kelas dan masa, kemudian simpan atau aktifkan.`);}catch(e){setMessage(e instanceof Error?e.message:'Muat naik gagal.');}finally{setBusy(false);}}
 async function save(action:string){setBusy(true);try{const r=await fetch('/api/form6-timetable',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data})}),b=await r.json();if(!r.ok)throw Error(b.error);if(action==='activate')setActive(b.updatedAt);setMessage(action==='activate'?'Jadual baharu aktif dalam Tugasan Saya dan loceng.':'Draf disimpan. Jadual aktif belum berubah.');}catch(e){setMessage(e instanceof Error?e.message:'Simpanan gagal.');}finally{setBusy(false);}}
 const errors=form6Errors(data),current=data.teachers[teacher];
 return <section className="form6-settings"><h2>Jadual Tingkatan Enam</h2><p>Muat naik jadual guru dan waktu PdPC secara berasingan. Muat naik baharu menggantikan bahagian tersebut dalam draf. Semak sebelum menggantikan jadual aktif.</p><p>{active?`Jadual aktif dikemas kini: ${new Date(active).toLocaleString('ms-MY',{timeZone:'Asia/Kuala_Lumpur'})}`:'Belum ada jadual aktif.'}</p>
 <div className="form6-grid">{[['teachers','Jadual guru (aSc)'],['times','Waktu PdPC mengikut hari']].map(([kind,label])=><label key={kind}>{label}<input type="file" accept="application/pdf,image/jpeg,image/png" disabled={busy} onChange={e=>{void upload(e.target.files?.[0],kind);e.target.value='';}}/><small>PDF, JPG atau PNG · maksimum 6 MB</small></label>)}</div>
 <p role="status">{message}</p>
 <h3>1. Padankan guru dan semak kelas</h3><label>Guru dalam dokumen<select value={teacher} onChange={e=>setTeacher(Number(e.target.value))}>{data.teachers.map((t,i)=><option key={i} value={i}>{t.userId?'':'⚠ '}{t.name}</option>)}</select></label>
 {current&&<fieldset><legend>{current.name}</legend><label>Akaun dalam direktori<select className={!current.userId?'form6-invalid':''} value={current.userId} onChange={e=>change({...data,teachers:data.teachers.map((t,i)=>i===teacher?{...t,userId:e.target.value}:t)})}><option value="">Pilih padanan nama</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>
 {current.lessons.map((l,i)=><div className="form6-row" key={i}>{(['day','start','end','subject','className'] as const).map(key=><label key={key}>{{day:'Hari',start:'Waktu mula',end:'Waktu akhir',subject:'Subjek',className:'Kelas'}[key]}{key==='day'?<select value={l.day} onChange={e=>change({...data,teachers:data.teachers.map((t,j)=>j===teacher?{...t,lessons:t.lessons.map((a,k)=>k===i?{...a,day:e.target.value}:a)}:t)})}>{schoolDays.map(d=><option key={d}>{d}</option>)}</select>:<input type={key==='start'||key==='end'?'number':'text'} min="1" max="30" value={l[key]} onChange={e=>change({...data,teachers:data.teachers.map((t,j)=>j===teacher?{...t,lessons:t.lessons.map((a,k)=>k===i?{...a,[key]:key==='start'||key==='end'?Number(e.target.value):e.target.value}:a)}:t)})}/>}</label>)}<button type="button" onClick={()=>change({...data,teachers:data.teachers.map((t,j)=>j===teacher?{...t,lessons:t.lessons.filter((_,k)=>k!==i)}:t)})}>Buang baris</button></div>)}
 <button type="button" onClick={()=>change({...data,teachers:data.teachers.map((t,i)=>i===teacher?{...t,lessons:[...t.lessons,{day:'Isnin',start:1,end:1,subject:'',className:''}]}:t)})}>Tambah kelas</button></fieldset>}
 <h3>2. Semak waktu PdPC</h3><label>Hari<select value={day} onChange={e=>setDay(e.target.value)}>{schoolDays.map(d=><option key={d}>{d}</option>)}</select></label>
 {data.times.map((t,i)=>t.day===day&&<div className="form6-row" key={i}>{(['period','startTime','endTime'] as const).map(key=><label key={key}>{{period:'Waktu',startTime:'Mula',endTime:'Tamat'}[key]}<input type={key==='period'?'number':'time'} min={key==='period'?'1':undefined} max={key==='period'?'30':undefined} value={t[key]} onChange={e=>change({...data,times:data.times.map((a,k)=>k===i?{...a,[key]:key==='period'?Number(e.target.value):e.target.value}:a)})}/></label>)}<button type="button" onClick={()=>change({...data,times:data.times.filter((_,k)=>k!==i)})}>Buang baris</button></div>)}
 <button type="button" onClick={()=>change({...data,times:[...data.times,{day,period:Math.max(0,...data.times.filter(t=>t.day===day).map(t=>t.period))+1,startTime:'',endTime:''}]})}>Tambah waktu {day}</button>
 {errors.length>0&&<div className="form6-invalid" role="alert"><strong>{errors.length} perkara perlu disemak</strong><ul>{errors.map((e,i)=><li key={i}>{e}</li>)}</ul></div>}
 <label className="form6-review"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>Saya telah menyemak semua nama, kelas dan masa dengan dokumen asal.</label>
 <div className="form6-grid"><button disabled={busy} onClick={()=>void save('save')}>Simpan draf</button><button disabled={busy||!reviewed||errors.length>0} onClick={()=>void save('activate')}>Aktifkan dan ganti jadual</button></div>
 </section>;
}
