'use client';
import {Clock3,Users,Upload,CalendarDays,Plus,CheckCircle2} from 'lucide-react';
import {useEffect,useState} from 'react';
import {schoolDays,form6Errors,type Form6Data} from './form6-model';
export function Form6Settings(){
 const [data,setData]=useState<Form6Data>({teachers:[],times:[]}),[users,setUsers]=useState<{id:string;name:string}[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[active,setActive]=useState(''),[teacher,setTeacher]=useState(0),[day,setDay]=useState('Isnin'),[reviewed,setReviewed]=useState(false),[manualUser,setManualUser]=useState(''),[section,setSection]=useState<'teachers'|'times'>('times');
 useEffect(()=>{fetch('/api/form6-timetable').then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error);setUsers(b.users);setData(b.versions.find((v:{id:string;data:Form6Data;updatedAt:string})=>v.id==='draft')?.data||b.versions.find((v:{id:string;data:Form6Data;updatedAt:string})=>v.id==='active')?.data||{teachers:[],times:[]});setActive(b.versions.find((v:{id:string;data:Form6Data;updatedAt:string})=>v.id==='active')?.updatedAt||'');}).catch(e=>setMessage(e.message));},[]);
 const change=(next:Form6Data)=>{setData(next);setReviewed(false);};
 async function upload(file:File|undefined,kind:string){if(!file)return;setBusy(true);setMessage('Membaca dokumen. Jadual aktif masih digunakan.');try{const form=new FormData();form.append('file',file);form.append('kind',kind);const r=await fetch('/api/form6-timetable',{method:'POST',body:form}),b=await r.json();if(!r.ok)throw Error(b.error);change({...data,[kind]:b.rows});setTeacher(0);setMessage(`${file.name} telah dibaca. Semak semua guru, kelas dan masa, kemudian simpan atau aktifkan.`);}catch(e){setMessage(e instanceof Error?e.message:'Muat naik gagal.');}finally{setBusy(false);}}
 async function save(action:string){setBusy(true);try{const r=await fetch('/api/form6-timetable',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data})}),b=await r.json();if(!r.ok)throw Error(b.error);if(action==='activate')setActive(b.updatedAt);setMessage(action==='activate'?'Jadual baharu aktif dalam Tugasan Saya dan loceng.':'Draf disimpan. Jadual aktif belum berubah.');}catch(e){setMessage(e instanceof Error?e.message:'Simpanan gagal.');}finally{setBusy(false);}}
 const errors=form6Errors(data),current=data.teachers[teacher];
 return <section className="form6-settings"><header className="form6-hero"><span className="form6-eyebrow">PENGURUSAN JADUAL</span><h2>Jadual Tingkatan Enam</h2><p>Satu tetapan waktu PdPC, dikongsi oleh semua guru. Urus kelas setiap guru secara berasingan.</p><div className="form6-metrics"><span><Users size={18}/><strong>{data.teachers.length}</strong> guru</span><span><Clock3 size={18}/><strong>{data.times.length}</strong> waktu PdPC</span></div><p className="form6-active">{active?`Jadual aktif dikemas kini: ${new Date(active).toLocaleString('ms-MY',{timeZone:'Asia/Kuala_Lumpur'})}`:'Draf · Belum diaktifkan'}</p></header>
 <div className="form6-tabs" role="group" aria-label="Bahagian jadual"><button type="button" aria-pressed={section==='times'} onClick={()=>setSection('times')}><Clock3 size={20}/><span>Waktu PdPC<small>Dikongsi semua guru</small></span></button><button type="button" aria-pressed={section==='teachers'} onClick={()=>setSection('teachers')}><Users size={20}/><span>Jadual guru<small>Kelas & padanan nama</small></span></button></div>
 <label className="form6-upload"><Upload size={22}/><strong>{section==='times'?'Muat naik waktu PdPC bersama':'Muat naik jadual guru (aSc)'}</strong><span>Ganti daripada fail atau isi secara manual di bawah.</span><input type="file" accept="application/pdf,image/jpeg,image/png" disabled={busy} onChange={e=>{void upload(e.target.files?.[0],section);e.target.value='';}}/><small>PDF, JPG atau PNG · maksimum 6 MB</small></label>
 <p role="status">{message}</p>
 {section==='teachers'&&<div className="form6-panel"><h3><Users size={20}/> Jadual setiap guru</h3>
 <fieldset><legend>Tambah guru secara manual</legend><p>Pilih guru daripada direktori, kemudian isi hari, waktu, subjek dan kelas.</p><label>Guru untuk ditambah<select value={manualUser} disabled={busy} onChange={e=>setManualUser(e.target.value)}><option value="">Pilih guru</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><button type="button" disabled={busy||!manualUser} onClick={()=>{const user=users.find(u=>u.id===manualUser);if(!user)return;const existing=data.teachers.findIndex(t=>t.userId===user.id);if(existing>=0){setTeacher(existing);setMessage('Guru ini sudah ada. Jadual beliau dipilih untuk disunting.');}else{setTeacher(data.teachers.length);change({...data,teachers:[...data.teachers,{name:user.name,userId:user.id,lessons:[{day:'Isnin',start:1,end:1,subject:'',className:''}]}]});setMessage('Guru ditambah dalam draf. Lengkapkan kelas dan waktu PdPC sebelum mengaktifkan.');}setManualUser('');}}>Tambah guru</button></fieldset>
 <label>Guru dalam jadual<select value={teacher} onChange={e=>setTeacher(Number(e.target.value))}>{data.teachers.map((t,i)=><option key={i} value={i}>{t.userId?'':'⚠ '}{t.name}</option>)}</select></label>
 {current&&<fieldset><legend>{current.name}</legend><label>Akaun dalam direktori<select className={!current.userId?'form6-invalid':''} value={current.userId} onChange={e=>change({...data,teachers:data.teachers.map((t,i)=>i===teacher?{...t,userId:e.target.value}:t)})}><option value="">Pilih padanan nama</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>
 {current.lessons.map((l,i)=><div className="form6-row" key={i}>{(['day','start','end','subject','className'] as const).map(key=><label key={key}>{{day:'Hari',start:'Waktu mula',end:'Waktu akhir',subject:'Subjek',className:'Kelas'}[key]}{key==='day'?<select value={l.day} onChange={e=>change({...data,teachers:data.teachers.map((t,j)=>j===teacher?{...t,lessons:t.lessons.map((a,k)=>k===i?{...a,day:e.target.value}:a)}:t)})}>{schoolDays.map(d=><option key={d}>{d}</option>)}</select>:<input type={key==='start'||key==='end'?'number':'text'} min="1" max="30" value={l[key]} onChange={e=>change({...data,teachers:data.teachers.map((t,j)=>j===teacher?{...t,lessons:t.lessons.map((a,k)=>k===i?{...a,[key]:key==='start'||key==='end'?Number(e.target.value):e.target.value}:a)}:t)})}/>}</label>)}<button type="button" onClick={()=>change({...data,teachers:data.teachers.map((t,j)=>j===teacher?{...t,lessons:t.lessons.filter((_,k)=>k!==i)}:t)})}>Buang baris</button></div>)}
 <button type="button" onClick={()=>change({...data,teachers:data.teachers.map((t,i)=>i===teacher?{...t,lessons:[...t.lessons,{day:'Isnin',start:1,end:1,subject:'',className:''}]}:t)})}>Tambah kelas</button></fieldset>}
 </div>}
 {section==='times'&&<div className="form6-panel"><h3><CalendarDays size={20}/> Waktu PdPC bersama</h3><p className="form6-shared-note"><Users size={20}/><span><strong>Isi sekali untuk semua guru Tingkatan Enam.</strong> Jadual setiap guru mengambil masa mula dan tamat daripada tetapan hari ini. Perubahan masa terpakai kepada semua guru selepas diaktifkan.</span></p><div className="form6-days" role="group" aria-label="Hari PdPC">{schoolDays.map(d=><button type="button" key={d} aria-pressed={day===d} onClick={()=>setDay(d)}>{d}<small>{data.times.filter(t=>t.day===d).length} waktu</small></button>)}</div>
 {data.times.filter(t=>t.day===day).length===0&&<p className="form6-empty">Belum ada waktu untuk {day}. Tambah waktu pertama atau muat naik helaian PdPC.</p>}
 {data.times.map((t,i)=>t.day===day&&<div className="form6-row form6-time-row" key={i}>{(['period','startTime','endTime'] as const).map(key=><label key={key}>{{period:'Waktu',startTime:'Mula',endTime:'Tamat'}[key]}<input type={key==='period'?'number':'time'} min={key==='period'?'1':undefined} max={key==='period'?'30':undefined} value={t[key]} onChange={e=>change({...data,times:data.times.map((a,k)=>k===i?{...a,[key]:key==='period'?Number(e.target.value):e.target.value}:a)})}/></label>)}<button type="button" onClick={()=>change({...data,times:data.times.filter((_,k)=>k!==i)})}>Buang baris</button></div>)}
 <button type="button" onClick={()=>change({...data,times:[...data.times,{day,period:Math.max(0,...data.times.filter(t=>t.day===day).map(t=>t.period))+1,startTime:'',endTime:''}]})}><Plus size={18}/> Tambah waktu {day}</button></div>}
 {errors.length>0&&<div className="form6-invalid" role="alert"><strong>{errors.length} perkara perlu disemak</strong><ul>{errors.map((e,i)=><li key={i}>{e}</li>)}</ul></div>}
 <div className="form6-publish"><h3><CheckCircle2 size={20}/> Simpan perubahan</h3><label className="form6-review"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>Saya mengesahkan semua nama, kelas dan masa adalah betul.</label>
 <div className="form6-grid"><button disabled={busy} onClick={()=>void save('save')}>Simpan draf</button><button disabled={busy||!reviewed||errors.length>0} onClick={()=>void save('activate')}>Aktifkan dan ganti jadual</button></div></div>
 </section>;
}
