'use client';
import {useEffect,useState} from 'react';
import {timingErrors,type MainstreamTimes} from './mainstream-times';
export function MainstreamSettings(){
 const [data,setData]=useState<MainstreamTimes|null>(null),[day,setDay]=useState('Isnin'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/mainstream-times').then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error);setData(b.data);}).catch(e=>setMessage(e.message));},[]);
 async function save(){if(!data)return;const errors=timingErrors(data);if(errors.length){setMessage(errors.join(' '));return;}setBusy(true);try{const r=await fetch('/api/mainstream-times',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),b=await r.json();if(!r.ok)throw Error(b.error);setMessage('Waktu PdPC disimpan. Jadual harian menggunakan masa ini.');}catch(e){setMessage(e instanceof Error?e.message:'Simpanan gagal.');}finally{setBusy(false);}}
 return <section className="form6-settings"><header className="form6-hero"><span className="form6-eyebrow">WAKTU PdPC</span><h2>Arus perdana</h2><p>Tingkatan 1–3: menengah bawah. Tingkatan 4–5: menengah atas. Masa dipilih mengikut hari dan kelas yang diajar.</p></header>{message&&<p role="status">{message}</p>}{data&&<><label>Hari <select value={day} onChange={e=>setDay(e.target.value)}>{['Isnin','Selasa','Rabu','Khamis','Jumaat'].map(d=><option key={d}>{d}</option>)}</select></label><div style={{display:'grid',gap:12,marginBlock:16}}>{data.times.map((t,index)=>t.day!==day?null:<div key={index} style={{display:'grid',gridTemplateColumns:'60px 1fr 1fr',gap:12,alignItems:'center'}}><strong>W{t.period}</strong>{(['startTime','endTime'] as const).map(field=><label key={field}>{field==='startTime'?'Mula':'Tamat'}<input style={{width:'100%',minWidth:0,fontSize:16}} type="time" value={t[field]} onChange={e=>setData({...data,times:data.times.map((v,i)=>i===index?{...v,[field]:e.target.value}:v)})}/></label>)}</div>)}</div><div style={{display:'flex',gap:16,flexWrap:'wrap'}}>{(['lowerBreak','upperBreak'] as const).map(field=><label key={field}>Waktu rehat {field==='lowerBreak'?'menengah bawah':'menengah atas'}<input type="number" min={1} max={30} value={data[field]} onChange={e=>setData({...data,[field]:Number(e.target.value)})}/></label>)}</div><p>Rehat menengah bawah: W{data.lowerBreak} · Menengah atas: W{data.upperBreak}. Waktu rehat tidak dihantar sebagai peringatan kelas.</p><button disabled={busy} onClick={()=>void save()}>{busy?'Menyimpan…':'Simpan waktu PdPC'}</button></>}</section>;
}
