"use client";
import {useEffect,useState} from 'react';
import {EvidenceAIAssistant} from "./evidence-ai-assistant";
import {managementFolders,managementPath} from './management-catalog';
import {ManagementSuggestionCard} from './management-suggestion-card';
import {suggestManagementMaterial} from './management-suggestions';
import {skasStandards} from './skas-catalog';
type Candidate={id:string;title:string;folderId:string;documentType:string;mappingStatus?:string;openUrl:string};
export function ManagementCandidates({year,onMapped}:{year:number;onMapped:()=>void}){
 const [items,setItems]=useState<Candidate[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState(''),[standard,setStandard]=useState('2'),[unit,setUnit]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setError('');fetch('/api/pengurusan?year='+year,{cache:'no-store',signal:AbortSignal.timeout(20000)}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(active)setItems(d.materials.filter((m:Candidate)=>!m.mappingStatus));}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[year,refresh]);
 async function map(e:React.FormEvent){e.preventDefault();await saveMapping(selected,standard,unit);}
 async function saveMapping(id:string,standardCode:string,unitName:string){if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/pengurusan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'map',id,standardCode,unitName}),signal:AbortSignal.timeout(20000)}),d=await r.json();if(!r.ok)throw Error(d.error);setSelected('');setRefresh(n=>n+1);onMapped();}catch(e){setError(e instanceof Error?e.message:'Pemetaan gagal.');}finally{setBusy(false);}}
 return <section className="management-centre"><h3>Perlu tetapkan standard · Pengurusan Sekolah</h3><p>Semua jenis bahan yang didaftarkan—carta organisasi, minit, pelan, analisis, sijil, gambar, fail dan pautan—boleh dipilih jika sesuai.</p>
 {loading?<p role="status">Membaca calon bahan…</p>:<><p>{items.length} bahan belum dipetakan bagi {year}</p>{items.map(item=><article className="management-form" key={item.id}><h4>{item.title}</h4><p>{managementPath(item.folderId)} · {item.documentType}</p><EvidenceAIAssistant title={item.title} context={`${managementPath(item.folderId)} · ${item.documentType}`} disabled={busy} onApply={m=>{setSelected(item.id);setStandard(m.standardCode);setUnit(m.unitName);}} applyLabel="Semak pemetaan ini"/><ManagementSuggestionCard doc={item} disabled={busy} onUse={s=>void saveMapping(item.id,s.standardCode,s.unitName)}/><div className="management-toolbar"><a target="_blank" rel="noopener noreferrer" href={item.openUrl}>Buka bahan</a><button disabled={busy} onClick={()=>{setSelected(item.id);const s=suggestManagementMaterial(item);setStandard(s?.standardCode||'2');setUnit(s?.unitName||managementPath(item.folderId).slice(0,120));}}>Pemetaan manual</button></div>{selected===item.id&&<form onSubmit={map}><p>Cadangan berdasarkan folder, jenis dokumen dan tajuk sahaja. Semak kandungan sebelum menyimpan.</p><label>Standard<select value={standard} onChange={e=>setStandard(e.target.value)}>{skasStandards.map(([c,n])=><option value={c} key={c}>{c} · {n}</option>)}</select></label><label>Unit / pecahan<input maxLength={120} required value={unit} onChange={e=>setUnit(e.target.value)}/></label><button disabled={busy}>{busy?'Memproses…':'Simpan untuk perakuan'}</button></form>}</article>)}</>}
 {error&&<div className="management-error" role="alert">{error}<button onClick={()=>setRefresh(n=>n+1)}>Cuba semula</button></div>}
 </section>;
}
