'use client';
import {useEffect,useState} from 'react';
import {defaultNotificationSettings,type NotificationSettings} from './notification-settings-model';
import './notification-automation.css';
type Delivery={taskId:string;name:string;status:string;title:string;error:string;updatedAt:string};
type Run={id:string;kind:string;status:string;startedAt:string;finishedAt:string|null;error:string};
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuala_Lumpur'}).format(new Date());
const timestamp=(s:string)=>new Date(s).toLocaleString('ms-MY',{timeZone:'Asia/Kuala_Lumpur',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
const kind=(id:string)=>id.startsWith('morning')?'Ringkasan pagi':id.startsWith('class')?'Kelas':id.startsWith('reminder')?'Peringatan relief':'Relief / tugasan';
export default function NotificationAutomation(){
 const [settings,setSettings]=useState<NotificationSettings>(defaultNotificationSettings),[date,setDate]=useState(localDate),[runs,setRuns]=useState<Run[]>([]),[deliveries,setDeliveries]=useState<Delivery[]>([]),[subscriptions,setSubscriptions]=useState<{name:string;devices:number}[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[filter,setFilter]=useState('all'),[query,setQuery]=useState('');
 const load=async(initial=false)=>{setLoading(true);setError('');try{const r=await fetch(`/api/notification-automation?date=${date}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);if(initial)setSettings(d.settings);setRuns(d.runs);setDeliveries(d.deliveries);setSubscriptions(d.subscriptions);}catch(e){setError((e as Error).message);}finally{setLoading(false)}};
 useEffect(()=>{void load(true)},[date]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');setMessage('');try{const r=await fetch('/api/notification-automation',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)}),d=await r.json();if(!r.ok)throw Error(d.error);setSettings(d.settings);setMessage('Tetapan disimpan. Penjadual akan menggunakan tetapan ini pada semakan seterusnya.');}catch(e){setError((e as Error).message);}finally{setSaving(false)}};
 const visible=deliveries.filter(d=>(filter==='all'||d.status===filter)&&(d.name||'').toLowerCase().includes(query.toLowerCase()));
 return <section className="automation-panel" aria-labelledby="automation-title"><header><span className="modal-overline">NOTIFIKASI AUTOMATIK</span><h3 id="automation-title">Ringkasan pagi & peringatan kelas</h3><p>Ubah masa dan mesej, kemudian semak penghantaran mengikut tarikh. Semua masa mengikut Malaysia.</p></header>
 {error&&<p role="alert" className="automation-error">{error}</p>}{message&&<p role="status">{message}</p>}
 <details><summary>Ubah tetapan & mesej notifikasi</summary><form onSubmit={save} className="automation-form"><label className="automation-check"><input type="checkbox" checked={settings.morningEnabled} onChange={e=>setSettings({...settings,morningEnabled:e.target.checked})}/>Aktifkan ringkasan pagi · Isnin–Jumaat</label><label>Masa ringkasan pagi<input type="time" required value={settings.morningTime} onChange={e=>setSettings({...settings,morningTime:e.target.value})}/></label><label>Tajuk ringkasan<input required maxLength={100} value={settings.morningTitle} onChange={e=>setSettings({...settings,morningTitle:e.target.value})}/></label><label>Ucapan pembuka<textarea required rows={3} maxLength={300} value={settings.morningGreeting} onChange={e=>setSettings({...settings,morningGreeting:e.target.value})}/></label><label>Ucapan penutup<textarea required rows={3} maxLength={300} value={settings.morningClosing} onChange={e=>setSettings({...settings,morningClosing:e.target.value})}/></label><p>Gunakan {'{nama}'} untuk nama cikgu. Bilangan waktu mengajar, relief, guru bertugas dan tugasan lain diisi secara automatik untuk setiap individu. Jika tidak hadir pada hari itu, mesej diganti dengan nama dan sebab e-Keberadaan: MC — semoga cepat sembuh; sebab lain — semoga urusan dipermudahkan.</p><label className="automation-check"><input type="checkbox" checked={settings.classEnabled} onChange={e=>setSettings({...settings,classEnabled:e.target.checked})}/>Peringatan sebelum kelas</label><label className="automation-check"><input type="checkbox" checked={settings.reliefEnabled} onChange={e=>setSettings({...settings,reliefEnabled:e.target.checked})}/>Peringatan sebelum relief</label><label>Berapa minit sebelum bermula?<input type="number" required min={5} max={60} value={settings.leadMinutes} onChange={e=>setSettings({...settings,leadMinutes:Number(e.target.value)})}/></label><button disabled={saving||loading}>{saving?'Menyimpan…':'Simpan tetapan'}</button></form></details>
 <div className="automation-controls"><label>Tarikh rekod<input type="date" required value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></label><button type="button" disabled={loading} onClick={()=>void load()}>{loading?'Menyemak…':'Segarkan rekod'}</button></div>
 <details><summary>Cuba semula ringkasan hari ini</summary><p>Hanya penerima yang belum berjaya akan dicuba, maksimum 35 peranti setiap percubaan. Mesej menggunakan tugasan terkini hari ini.</p><button type="button" disabled={saving} onClick={async()=>{setSaving(true);setError('');try{const r=await fetch('/api/notification-automation',{method:'POST'}),d=await r.json();if(!r.ok)throw Error(d.error);setMessage(d.message);}catch(e){setError((e as Error).message);}finally{setSaving(false)}}}>Cuba semula penerima belum berjaya</button></details>
 <div className="automation-counts"><div><b>{deliveries.filter(d=>d.status==='sent').length}</b><span>Berjaya ke pelayan push</span></div><div><b>{deliveries.filter(d=>d.status==='failed').length}</b><span>Gagal</span></div><div><b>{deliveries.filter(d=>d.status==='sending').length}</b><span>Dalam proses / tergendala</span></div></div><p>“Berjaya” bermaksud pelayan push menerima mesej. Ia belum mengesahkan mesej dipaparkan atau dibaca pada telefon. Kiraan mengikut peranti; maksimum 1,000 rekod terkini bagi tarikh ini.</p>
 <div className="automation-controls"><label>Status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Semua status</option><option value="sent">Berjaya</option><option value="failed">Gagal</option><option value="sending">Dalam proses / tergendala</option></select></label><label>Cari penerima<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nama cikgu"/></label></div>
 <div className="automation-records" aria-busy={loading}>{!loading&&!visible.length&&<p>Tiada rekod penghantaran untuk pilihan ini. Ini tidak bermaksud penghantaran berjaya. Semak proses penjadual di bawah.</p>}{visible.map((d,i)=><article key={d.taskId+i}><header><strong>{d.name||'Pengguna tidak tersedia'}</strong><span>{d.status==='sent'?'Berjaya':d.status==='failed'?'Gagal':'Dalam proses / tergendala'}</span></header><p>{d.title||kind(d.taskId)}</p><small>{kind(d.taskId)} · {timestamp(d.updatedAt)}</small>{d.error&&<p className="automation-error">{d.error}</p>}</article>)}</div>
 <details><summary>Log penjadual · {runs.length} proses terkini</summary><p>“Selesai” bermaksud semakan tamat; ia tidak semestinya menghantar mesej jika belum tiba masa atau tiada penerima. Proses melebihi 3 minit ditandakan tergendala. Log terperinci bermula selepas kemas kini ini.</p>{!runs.length&&<p>Tiada rekod proses untuk tarikh ini.</p>}{runs.map(r=><p key={r.id}><strong>{r.kind.startsWith('morning')?'Ringkasan pagi':r.kind==='class'?'Kelas':'Relief'}</strong> · {timestamp(r.startedAt)} · {r.status==='completed'?'Selesai':r.status==='failed'?'Gagal':Date.now()-Date.parse(r.startedAt)>180000?'Tergendala':'Sedang berjalan'}{r.error&&` — ${r.error}`}</p>)}</details>
 <details><summary>Pengguna tanpa peranti notifikasi · {subscriptions.filter(s=>!s.devices).length}</summary><p>Pengguna ini perlu mengaktifkan notifikasi pada peranti mereka sebelum boleh menerima push.</p>{subscriptions.filter(s=>!s.devices).map(s=><p key={s.name}>{s.name}</p>)}</details></section>;
}
