'use client';
import {useEffect,useState} from 'react';
import {inManagementFolder,managementPath,managementFolders,managementSections,managementDocumentTypes} from './management-catalog';
export type Linked={documentType:string;mappingBasis:string;sourceModule:string;id:string;title:string;category:string;folderId:string;openUrl:string};
export function OprManagementLinks({year,folder,kind,query,admin,yearOpen,onReports}:{year:number;folder:string;kind:string;query:string;admin:boolean;yearOpen:boolean;onReports:(reports:Linked[])=>void}){
 const [reports,setReports]=useState<Linked[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 const [editing,setEditing]=useState<Linked|null>(null),[selected,setSelected]=useState(''),[documentType,setDocumentType]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;setLoading(true);setError('');setEditing(null);onReports([]);fetch('/api/opr-management?year='+year,{cache:'no-store',signal:AbortSignal.timeout(20000)}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error);if(active){setReports(data.reports);onReports(data.reports);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[year,refresh,onReports]);
 const shown=reports.filter(r=>(!folder||inManagementFolder(r.folderId,folder))&&(!kind||r.documentType===kind)&&(!query||[r.title,r.category,managementPath(r.folderId)].join(' ').toLowerCase().includes(query.toLowerCase())));
 async function save(e:React.FormEvent){
  e.preventDefault();if(!editing||busy)return;setBusy(true);setError('');
  try{const response=await fetch('/api/opr-management',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:editing.id,folderId:selected,documentType}),signal:AbortSignal.timeout(20000)}),data=await response.json();if(!response.ok)throw Error(data.error);
   const next=reports.map(r=>r.id===editing.id?{...r,folderId:selected,documentType,mappingBasis:'manual'}:r);setReports(next);onReports(next);setEditing(null);setMessage('Folder disimpan: '+managementPath(selected)+'. Pemetaan SK@S tidak diubah.');
  }catch(e){setError(e instanceof Error?e.message:'Simpanan gagal.');}finally{setBusy(false);}
 }
 return <section className="management-materials"><h3>Laporan dan arkib dalam folder ini ({shown.length})</h3><p>Rujukan kepada fail asal. Pilihan folder di sini berasingan daripada pemetaan SK@S.</p><button onClick={()=>setRefresh(n=>n+1)} disabled={loading||busy}>Segarkan rujukan laporan</button>
 {message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}
 {editing&&<form className="management-form" onSubmit={save}><h3>Folder dan jenis dokumen</h3><p>{editing.title}</p><fieldset disabled={busy}><label>Folder destinasi<select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Pilih folder</option>{managementSections.map(section=><optgroup key={section.id} label={section.name}>{managementFolders.filter(f=>inManagementFolder(f.id,section.id)).map(f=><option key={f.id} value={f.id}>{managementPath(f.id)}</option>)}</optgroup>)}</select></label><label>Jenis dokumen<select required value={documentType} onChange={e=>setDocumentType(e.target.value)}>{managementDocumentTypes.map(t=><option key={t}>{t}</option>)}</select></label><div className="management-toolbar"><button type="submit">{busy?'Menyimpan…':'Simpan padanan'}</button><button type="button" onClick={()=>setEditing(null)}>Batal</button></div></fieldset></form>}
 {loading?<p role="status">Membaca rujukan laporan…</p>:!error&&(shown.length?shown.map(r=><article key={r.id}><div><h4>{r.title}</h4><p>{r.folderId?managementPath(r.folderId):'Belum dipadankan. Pentadbir boleh memilih folder di sini.'}</p><p>{r.mappingBasis==='manual'?'Folder dipilih oleh pentadbir.':'Folder mengikut maklumat laporan asal.'}</p><p>{r.documentType}</p><p>{r.sourceModule} · {r.category}</p><div className="management-toolbar">{r.openUrl&&<a href={r.openUrl} target="_blank" rel="noopener noreferrer">Buka laporan asal</a>}{admin&&<button disabled={!yearOpen||busy} onClick={()=>{setEditing(r);setSelected(r.folderId);setDocumentType(r.documentType);setMessage('');}}>{r.folderId?'Ubah folder / jenis':'Pilih folder / jenis'}</button>}</div></div></article>):<p>Tiada laporan dalam folder dan tahun ini. Bahan belum dipadankan boleh dilihat di Semua bahagian.</p>)}
 </section>;
}
