"use client";
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {sspaGrades} from './profile-model';
type User={id:string;name:string;email:string;position:string;grade:string;role:string;avatarDataUrl?:string};
type Item={id:string;userId:string;title:string;issuer:string;awardDate:string;featured:number;fileName:string;teacherName:string;evidenceStatus:string};
async function responseData(response:Response){const data=await response.json();if(!response.ok)throw new Error(data.error||'Tindakan tidak berjaya.');return data;}
export function ProfileCard({user,close,save,updatePhoto,logout,notify,pushState,enableNotifications}:{user:User;close:()=>void;save:(p:{name:string;position:string;grade:string})=>Promise<void>;updatePhoto:(file?:File)=>Promise<void>;logout:()=>void;notify:(m:string)=>void;pushState:string;enableNotifications:()=>Promise<void>}){
 const [view,setView]=useState('profile'),[grade,setGrade]=useState(user.grade),[busy,setBusy]=useState(false),[items,setItems]=useState<Item[]>([]),[error,setError]=useState('');
 const [photo,setPhoto]=useState<HTMLImageElement|null>(null),[zoom,setZoom]=useState(1),[panX,setPanX]=useState(0),[panY,setPanY]=useState(0),[avatarError,setAvatarError]=useState(false);
 const canvas=useRef<HTMLCanvasElement>(null),fileInput=useRef<HTMLInputElement>(null);
 const [form,setForm]=useState({id:crypto.randomUUID(),title:'',issuer:'',awardDate:''}),[file,setFile]=useState<File|null>(null);
 const load=async()=>{try{const data=await responseData(await fetch('/api/portfolio',{cache:'no-store'}));setItems(data.items);}catch(e){setError(e instanceof Error?e.message:'Portfolio tidak dapat dibaca.');}};
 useEffect(()=>{void load();},[]);
 useEffect(()=>setAvatarError(false),[user.avatarDataUrl]);
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!busy)close();};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler);},[busy,close]);
 useEffect(()=>{if(!photo||!canvas.current)return;const ctx=canvas.current.getContext('2d');if(!ctx)return;const w=420,h=540,scale=Math.max(w/photo.naturalWidth,h/photo.naturalHeight)*zoom,dw=photo.naturalWidth*scale,dh=photo.naturalHeight*scale;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.drawImage(photo,(w-dw)/2-(dw-w)*panX/2,(h-dh)/2-(dh-h)*panY/2,dw,dh);},[photo,zoom,panX,panY,view]);
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Tindakan tidak berjaya.');}finally{setBusy(false);}};
 const selectPhoto=async(file?:File)=>{if(!file)return;await run(async()=>{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>20_000_000)throw Error('Pilih JPG, PNG atau WebP, maksimum 20 MB.');const url=URL.createObjectURL(file),image=new Image();try{image.src=url;await image.decode();setPhoto(image);setZoom(1);setPanX(0);setPanY(0);setView('photo');}finally{URL.revokeObjectURL(url);}});};
 const savePhoto=()=>run(async()=>{const c=canvas.current;if(!c)throw Error('Gambar belum sedia.');const blob=await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('Gambar tidak dapat diproses.')),'image/jpeg',.88));await updatePhoto(new File([blob],'profil.jpg',{type:'image/jpeg'}));setPhoto(null);setView('profile');});
 const upload=()=>run(async()=>{if(!file||!form.title.trim())throw Error('Isi nama kepakaran dan pilih sijil atau surat.');const payload=new FormData();Object.entries(form).forEach(([key,value])=>payload.set(key,value));payload.set('file',file);await responseData(await fetch('/api/portfolio',{method:'POST',body:payload}));setForm({id:crypto.randomUUID(),title:'',issuer:'',awardDate:''});setFile(null);if(fileInput.current)fileInput.current.value='';await load();notify('Portfolio disimpan ke Drive sekolah dan calon evidens SK@S.');});
 const feature=(id:string)=>run(async()=>{const ids=items.filter(i=>i.featured).map(i=>i.id);const next=ids.includes(id)?ids.filter(v=>v!==id):[...ids,id];if(next.length>2)throw Error('Hanya dua kepakaran boleh ditonjolkan. Nyahpilih salah satu dahulu.');await responseData(await fetch('/api/portfolio',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:next})}));await load();});
 return createPortal(<div className="staff-profile-backdrop"><section className="staff-profile-card" role="dialog" aria-modal="true" aria-label="Profil dan portfolio pengguna"><button className="staff-profile-close" aria-label="Tutup profil" onClick={close} disabled={busy}>×</button>
 <div className="staff-passport">{user.avatarDataUrl&&!avatarError?<img src={user.avatarDataUrl} onError={()=>setAvatarError(true)} alt={`Gambar ${user.name}`}/>:<span>{user.name.split(/\s+/).filter(Boolean).slice(0,2).map(s=>s[0]).join('')}</span>}</div>
 <h2>{user.name}</h2><p className="staff-profile-meta">{user.email}<br/>{user.position} · {user.grade}</p>
 {view==='profile'&&<><div className="staff-expertise-badges">{items.filter(i=>i.featured).slice(0,2).map(i=><span key={i.id}>★ {i.title}</span>)}</div><div className="staff-profile-actions"><button onClick={()=>setView('edit')}>Kemas kini profil</button><label>Kemas kini gambar<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void selectPhoto(e.target.files?.[0])}/></label><button onClick={()=>setView('portfolio')}>Kemas kini portfolio ({items.length})</button><button disabled={pushState==='loading'||pushState==='enabled'} onClick={()=>void enableNotifications()}>{pushState==='enabled'?'Notifikasi aktif':'Aktifkan notifikasi'}</button><button onClick={logout}>Log keluar</button></div></>}
 {view==='edit'&&<form className="staff-profile-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await save({name:user.name,position:user.position,grade});setView('profile');});}}><p>Nama, e-mel dan jawatan hanya boleh dikemas kini oleh pentadbir melalui Pengurusan Pengguna.</p><label>Nama<input value={user.name} readOnly/></label><label>E-mel DELIMa<input value={user.email} readOnly/></label><label>Jawatan<input value={user.position} readOnly/></label><label>Gred SSPA<select value={grade} onChange={e=>setGrade(e.target.value)}>{!sspaGrades.includes(user.grade)&&<option value={user.grade}>{user.grade||'Pilih gred'}</option>}{sspaGrades.map(g=><option key={g}>{g}</option>)}</select></label><div className="staff-profile-actions"><button type="button" disabled={busy} onClick={()=>setView('profile')}>Batal</button><button disabled={busy}>{busy?'Menyimpan…':'Simpan gred'}</button></div></form>}
 {view==='photo'&&<div className="staff-profile-form"><h3>Laraskan gambar pasport</h3><canvas ref={canvas} width={420} height={540} className="staff-crop-preview"/><label>Zum masuk / keluar<input type="range" min="1" max="3" step=".01" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><label>Kedudukan kiri / kanan<input type="range" min="-1" max="1" step=".01" value={panX} onChange={e=>setPanX(Number(e.target.value))}/></label><label>Kedudukan atas / bawah<input type="range" min="-1" max="1" step=".01" value={panY} onChange={e=>setPanY(Number(e.target.value))}/></label><div className="staff-profile-actions"><button disabled={busy} onClick={()=>{setPhoto(null);setView('profile');}}>Batal</button><button disabled={busy} onClick={()=>void savePhoto()}>{busy?'Menyimpan…':'Simpan gambar'}</button></div></div>}
 {view==='portfolio'&&<div className="staff-profile-form"><button disabled={busy} onClick={()=>setView('profile')}>← Kembali ke profil</button><h3>Portfolio kepakaran</h3><p>Semua bahan disimpan sebagai calon evidens SK@S. Pilih maksimum dua untuk ditonjolkan pada profil.</p><form onSubmit={e=>{e.preventDefault();void upload();}}><label>Nama kepakaran / pengiktirafan<input required maxLength={180} placeholder="Contoh: Google Certified Educator" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Penganjur / badan pengiktiraf<input value={form.issuer} onChange={e=>setForm({...form,issuer:e.target.value})}/></label><label>Tarikh sijil / surat<input type="date" value={form.awardDate} onChange={e=>setForm({...form,awardDate:e.target.value})}/></label><label>Sijil atau surat sokongan (maksimum 8 MB)<input ref={fileInput} type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.docx" required onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button disabled={busy}>{busy?'Menyimpan ke Drive sekolah…':'Muat naik portfolio'}</button></form>{items.map(item=><article className="staff-portfolio-item" key={item.id}><h4>{item.title}</h4><p>{item.issuer} {item.awardDate}</p><small>SK@S: {item.evidenceStatus==='approved'?'Diperakui':'Menunggu semakan / perakuan'}</small><a href={`/api/pengurusan?file=${item.id}`} target="_blank" rel="noreferrer">Buka sijil / surat</a><button disabled={busy} aria-pressed={Boolean(item.featured)} onClick={()=>void feature(item.id)}>{item.featured?'★ Ditonjolkan — nyahpilih':'☆ Tonjolkan pada profil'}</button></article>)}</div>}
 {error&&<p className="staff-profile-error" role="alert">{error}</p>}</section></div>,document.body);
}

export function StaffExpertiseList(){
 const [items,setItems]=useState<Item[]>([]),[users,setUsers]=useState<Array<{id:string;name:string;position:string}>>([]),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch('/api/portfolio?all=1',{cache:'no-store'}).then(responseData).then(data=>{setItems(data.items);setUsers(data.users);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 const q=search.trim().toLocaleLowerCase('ms-MY');const filtered=users.filter(u=>[u.name,...items.filter(i=>i.userId===u.id).map(i=>i.title+' '+i.issuer)].join(' ').toLocaleLowerCase('ms-MY').includes(q));
 return <section className="staff-expertise-admin"><h2>Senarai Kepakaran Guru</h2><label>Cari nama guru atau kepakaran<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Contoh: Azwan, Apple Teacher, Woodball"/></label>{loading?<p>Memuatkan senarai…</p>:<p>{filtered.length} warga sekolah · {items.length} rekod kepakaran</p>}{error&&<p role="alert">{error}</p>}{filtered.map(u=><article key={u.id}><h3>{u.name}</h3><p>{u.position}</p>{items.filter(i=>i.userId===u.id).length?items.filter(i=>i.userId===u.id).map(i=><div className="staff-portfolio-item" key={i.id}><strong>{i.featured?'★ ':''}{i.title}</strong><p>{i.issuer} · {i.awardDate}</p><small>{i.featured?'Ditonjolkan pada profil · ':''}SK@S: {i.evidenceStatus==='approved'?'Diperakui':'Menunggu semakan / perakuan'}</small><a href={`/api/pengurusan?file=${i.id}`} target="_blank" rel="noreferrer">Buka sijil / surat</a></div>):<p>Belum ada portfolio dimuat naik.</p>}</article>)}</section>;
}
