import { env } from "cloudflare:workers";

type GoogleIdentity={aud:string;email:string;email_verified:string|boolean};
type ContentBody={id?:string;kind?:"announcement"|"event";title?:string;body?:string;audience?:string;publishedAt?:string;eventDate?:string;endDate?:string;category?:string;details?:string};
const CLIENT_ID="700702672944-20sjvug0albitl36cm671s7h19k57pc4.apps.googleusercontent.com";
const clean=(value:unknown,max=500)=>typeof value==="string"?value.trim().slice(0,max):"";

async function prepare(){await env.DB.batch([
  env.DB.prepare("CREATE TABLE IF NOT EXISTS portal_settings (setting_key TEXT PRIMARY KEY,setting_value TEXT NOT NULL,updated_at TEXT NOT NULL)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS portal_users (id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,name TEXT NOT NULL,position TEXT NOT NULL DEFAULT '',grade TEXT NOT NULL DEFAULT '',role TEXT NOT NULL DEFAULT 'teacher',status TEXT NOT NULL DEFAULT 'active',show_directory INTEGER NOT NULL DEFAULT 1,deleted_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS portal_announcements (id TEXT PRIMARY KEY,title TEXT NOT NULL,body TEXT NOT NULL,audience TEXT NOT NULL DEFAULT 'Semua',published_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'published',created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS portal_calendar (id TEXT PRIMARY KEY,title TEXT NOT NULL,event_date TEXT NOT NULL,end_date TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'Sekolah',details TEXT NOT NULL DEFAULT '',created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS admin_audit_logs (id TEXT PRIMARY KEY,actor_email TEXT NOT NULL,action TEXT NOT NULL,target_email TEXT NOT NULL,created_at TEXT NOT NULL)"),
]);}
async function admin(request:Request){const token=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!token)return null;const response=await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${encodeURIComponent(token)}`);if(!response.ok)return null;const google=await response.json() as GoogleIdentity;if(google.aud!==CLIENT_ID||String(google.email_verified)!=="true")return null;return env.DB.prepare("SELECT id,email,name,role FROM portal_users WHERE email=? AND status='active' AND deleted_at IS NULL AND role IN ('admin','super_admin')").bind(google.email.toLowerCase()).first<Record<string,string>>();}
async function log(actor:string,action:string,target:string){await env.DB.prepare("INSERT INTO admin_audit_logs(id,actor_email,action,target_email,created_at) VALUES(?,?,?,?,?)").bind(crypto.randomUUID(),actor,action,target,new Date().toISOString()).run();}

export async function GET(){try{await prepare();const [settings,announcements,events,people]=await Promise.all([env.DB.prepare("SELECT setting_key,setting_value FROM portal_settings").all<Record<string,string>>(),env.DB.prepare("SELECT id,title,body,audience,published_at AS publishedAt FROM portal_announcements WHERE status='published' ORDER BY published_at DESC LIMIT 30").all(),env.DB.prepare("SELECT id,title,event_date AS eventDate,end_date AS endDate,category,details FROM portal_calendar ORDER BY event_date ASC LIMIT 150").all(),env.DB.prepare("SELECT id,name,position,grade FROM portal_users WHERE status='active' AND deleted_at IS NULL AND show_directory=1 ORDER BY name").all<Record<string,string>>()]);const leaders=people.results.filter(person=>/(pengetua|penolong kanan|guru kanan mata pelajaran)/i.test(person.position));return Response.json({settings:Object.fromEntries(settings.results.map(row=>[row.setting_key,row.setting_value])),announcements:announcements.results,events:events.results,leaders});}catch(error){console.error("Portal content read",error);return Response.json({error:"Kandungan portal tidak dapat dibaca."},{status:500});}}

export async function POST(request:Request){try{await prepare();const me=await admin(request);if(!me)return Response.json({error:"Akses pentadbir diperlukan."},{status:403});const body=await request.json() as ContentBody,now=new Date().toISOString(),id=crypto.randomUUID(),title=clean(body.title,180);if(!title)return Response.json({error:"Tajuk perlu diisi."},{status:400});if(body.kind==="announcement"){await env.DB.prepare("INSERT INTO portal_announcements(id,title,body,audience,published_at,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,'published',?,?,?)").bind(id,title,clean(body.body,2500),clean(body.audience,50)||"Semua",clean(body.publishedAt,30)||now.slice(0,10),me.email,now,now).run();}else{const date=clean(body.eventDate,10);if(!date)return Response.json({error:"Tarikh aktiviti perlu diisi."},{status:400});await env.DB.prepare("INSERT INTO portal_calendar(id,title,event_date,end_date,category,details,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(id,title,date,clean(body.endDate,10)||date,clean(body.category,60)||"Sekolah",clean(body.details,1200),me.email,now,now).run();}await log(me.email,`${body.kind}_create`,title);return Response.json({success:true,id});}catch(error){console.error("Portal content create",error);return Response.json({error:"Kandungan tidak dapat disimpan."},{status:500});}}

export async function DELETE(request:Request){try{await prepare();const me=await admin(request);if(!me)return Response.json({error:"Akses pentadbir diperlukan."},{status:403});const url=new URL(request.url),id=clean(url.searchParams.get("id"),80),kind=url.searchParams.get("kind");if(kind==="announcement")await env.DB.prepare("DELETE FROM portal_announcements WHERE id=?").bind(id).run();else await env.DB.prepare("DELETE FROM portal_calendar WHERE id=?").bind(id).run();await log(me.email,`${kind}_delete`,id);return Response.json({success:true});}catch(error){console.error("Portal content delete",error);return Response.json({error:"Kandungan tidak dapat dipadam."},{status:500});}}

export async function PUT(request:Request){try{await prepare();const me=await admin(request);if(!me)return Response.json({error:"Akses pentadbir diperlukan."},{status:403});const body=await request.json() as {settings?:Record<string,string>},allowed=new Set(["school_name","school_code","school_grade","school_type","school_founded","school_motto","school_vision","school_mission","school_history","school_email","school_phone","school_address","footer_notice"]),entries=Object.entries(body.settings||{}).filter(([key])=>allowed.has(key)),now=new Date().toISOString();if(entries.length)await env.DB.batch(entries.map(([key,value])=>env.DB.prepare("INSERT INTO portal_settings(setting_key,setting_value,updated_at) VALUES(?,?,?) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value,updated_at=excluded.updated_at").bind(key,clean(value,2500),now)));await log(me.email,"school_profile_update",entries.map(([key])=>key).join(","));return Response.json({success:true});}catch(error){console.error("Portal profile update",error);return Response.json({error:"Profil sekolah tidak dapat disimpan."},{status:500});}}
