import { env } from "cloudflare:workers";

type GoogleIdentity={aud:string;email:string;email_verified:string|boolean};
type ContentBody={id?:string;kind?:"announcement"|"event";title?:string;body?:string;audience?:string;publishedAt?:string;endsAt?:string;imageBase64?:string;imageMimeType?:string;eventDate?:string;endDate?:string;category?:string;details?:string};
const CLIENT_ID="700702672944-20sjvug0albitl36cm671s7h19k57pc4.apps.googleusercontent.com";
const clean=(value:unknown,max=500)=>typeof value==="string"?value.trim().slice(0,max):"";

async function prepare(){await env.DB.batch([
  env.DB.prepare("CREATE TABLE IF NOT EXISTS portal_settings (setting_key TEXT PRIMARY KEY,setting_value TEXT NOT NULL,updated_at TEXT NOT NULL)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS portal_users (id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,name TEXT NOT NULL,position TEXT NOT NULL DEFAULT '',grade TEXT NOT NULL DEFAULT '',role TEXT NOT NULL DEFAULT 'teacher',status TEXT NOT NULL DEFAULT 'active',show_directory INTEGER NOT NULL DEFAULT 1,show_org_chart INTEGER NOT NULL DEFAULT 0,org_position TEXT NOT NULL DEFAULT '',org_order REAL NOT NULL DEFAULT 999,deleted_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS portal_announcements (id TEXT PRIMARY KEY,title TEXT NOT NULL,body TEXT NOT NULL,audience TEXT NOT NULL DEFAULT 'Semua',published_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'published',created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS portal_calendar (id TEXT PRIMARY KEY,title TEXT NOT NULL,event_date TEXT NOT NULL,end_date TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'Sekolah',details TEXT NOT NULL DEFAULT '',created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)"),
  env.DB.prepare("CREATE TABLE IF NOT EXISTS admin_audit_logs (id TEXT PRIMARY KEY,actor_email TEXT NOT NULL,action TEXT NOT NULL,target_email TEXT NOT NULL,created_at TEXT NOT NULL)"),
]);try{await env.DB.prepare("ALTER TABLE portal_announcements ADD COLUMN ends_at TEXT NOT NULL DEFAULT ''").run();}catch{}try{await env.DB.prepare("ALTER TABLE portal_announcements ADD COLUMN image_key TEXT NOT NULL DEFAULT ''").run();}catch{}try{await env.DB.prepare("ALTER TABLE portal_users ADD COLUMN show_org_chart INTEGER").run();}catch{}try{await env.DB.prepare("ALTER TABLE portal_users ADD COLUMN org_position TEXT NOT NULL DEFAULT ''").run();}catch{}try{await env.DB.prepare("ALTER TABLE portal_users ADD COLUMN org_order REAL NOT NULL DEFAULT 999").run();}catch{}
await env.DB.prepare("UPDATE portal_users SET position='Guru Kanan Mata Pelajaran Bahasa' WHERE email='g-55165688@moe-dl.edu.my' AND position='Guru Akademik Biasa'").run();
await env.DB.prepare(`UPDATE portal_users SET show_org_chart=1,org_position=position,org_order=CASE
  WHEN lower(position) LIKE '%pengetua%' AND lower(position) NOT LIKE '%penolong%' THEN 0
  WHEN lower(position) LIKE '%pentadbiran%' THEN 100 WHEN lower(position) LIKE '%hal ehwal murid%' THEN 110
  WHEN lower(position) LIKE '%kokurikulum%' AND lower(position) LIKE '%penolong kanan%' THEN 120
  WHEN lower(position) LIKE '%tingkatan enam%' AND lower(position) LIKE '%penolong kanan%' THEN 130
  WHEN lower(position) LIKE '%bahasa%' THEN 200 WHEN lower(position) LIKE '%sains & matematik%' THEN 210
  WHEN lower(position) LIKE '%kemanusiaan%' THEN 220 WHEN lower(position) LIKE '%teknik & vokasional%' THEN 230
  WHEN lower(position) LIKE '%pendidikan islam%' THEN 240 ELSE 900 END
  WHERE show_org_chart=0 AND org_position='' AND (lower(position) LIKE '%pengetua%' OR lower(position) LIKE '%penolong kanan%' OR lower(position) LIKE '%guru kanan mata pelajaran%')`).run();
await env.DB.prepare(`UPDATE portal_users SET
  show_org_chart=CASE WHEN lower(position) LIKE '%pengetua%' OR lower(position) LIKE '%penolong kanan%' OR lower(position) LIKE '%guru kanan mata pelajaran%' THEN 1 ELSE 0 END,
  org_position=CASE WHEN org_position='' THEN position ELSE org_position END,
  org_order=CASE
    WHEN lower(position) LIKE '%pengetua%' AND lower(position) NOT LIKE '%penolong%' THEN 0
    WHEN lower(position) LIKE '%pentadbiran%' THEN 100
    WHEN lower(position) LIKE '%hal ehwal murid%' THEN 110
    WHEN lower(position) LIKE '%kokurikulum%' AND lower(position) LIKE '%penolong kanan%' THEN 120
    WHEN lower(position) LIKE '%tingkatan enam%' AND lower(position) LIKE '%penolong kanan%' THEN 130
    WHEN lower(position) LIKE '%bahasa%' THEN 200
    WHEN lower(position) LIKE '%sains & matematik%' THEN 210
    WHEN lower(position) LIKE '%kemanusiaan%' THEN 220
    WHEN lower(position) LIKE '%teknik & vokasional%' THEN 230
    WHEN lower(position) LIKE '%pendidikan islam%' THEN 240
    ELSE 900 END
  WHERE show_org_chart IS NULL`).run();}
async function admin(request:Request){const token=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!token)return null;const response=await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${encodeURIComponent(token)}`);if(!response.ok)return null;const google=await response.json() as GoogleIdentity;if(google.aud!==CLIENT_ID||String(google.email_verified)!=="true")return null;return env.DB.prepare("SELECT id,email,name,role FROM portal_users WHERE email=? AND status='active' AND deleted_at IS NULL AND role IN ('admin','super_admin')").bind(google.email.toLowerCase()).first<Record<string,string>>();}
async function viewer(request:Request){const token=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!token)return null;const response=await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${encodeURIComponent(token)}`);if(!response.ok)return null;const google=await response.json() as GoogleIdentity;if(google.aud!==CLIENT_ID||String(google.email_verified)!=="true")return null;return env.DB.prepare("SELECT id,email,name,role FROM portal_users WHERE email=? AND status='active' AND deleted_at IS NULL").bind(google.email.toLowerCase()).first<Record<string,string>>();}
async function log(actor:string,action:string,target:string){await env.DB.prepare("INSERT INTO admin_audit_logs(id,actor_email,action,target_email,created_at) VALUES(?,?,?,?,?)").bind(crypto.randomUUID(),actor,action,target,new Date().toISOString()).run();}
async function imageDataUrl(key:string){if(!key)return "";const object=await env.FILES.get(key);if(!object)return "";const bytes=new Uint8Array(await object.arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return `data:${object.httpMetadata?.contentType||"image/jpeg"};base64,${btoa(binary)}`;}

export async function GET(request:Request){try{await prepare();const mode=new URL(request.url).searchParams.get("view"),person=mode?await viewer(request):null;if(mode&&!person)return Response.json({error:"Log masuk warga sekolah diperlukan."},{status:403});if(mode==="admin"&&!['admin','super_admin'].includes(person?.role||""))return Response.json({error:"Akses pentadbir diperlukan."},{status:403});const fields="id,title,body,audience,published_at AS publishedAt,ends_at AS endsAt,image_key AS imageKey";const announcementSql=mode==="admin"?`SELECT ${fields} FROM portal_announcements WHERE status='published' ORDER BY published_at DESC LIMIT 100`:mode==="staff"?`SELECT ${fields} FROM portal_announcements WHERE status='published' AND audience='Guru & Staf' AND published_at<=date('now') AND (ends_at='' OR ends_at>=date('now')) ORDER BY published_at DESC LIMIT 10`:`SELECT ${fields} FROM portal_announcements WHERE status='published' AND audience!='Guru & Staf' AND published_at<=date('now') AND (ends_at='' OR ends_at>=date('now')) ORDER BY published_at DESC LIMIT 30`;const [settings,announcementRows,events,people]=await Promise.all([env.DB.prepare("SELECT setting_key,setting_value FROM portal_settings").all<Record<string,string>>(),env.DB.prepare(announcementSql).all<Record<string,string>>(),env.DB.prepare("SELECT id,title,event_date AS eventDate,end_date AS endDate,category,details FROM portal_calendar ORDER BY event_date ASC LIMIT 150").all(),env.DB.prepare("SELECT u.id,u.name,u.position,u.grade,u.org_position AS orgPosition,u.org_order AS orgOrder,p.avatar_key AS avatarKey FROM portal_users u LEFT JOIN portal_profiles p ON p.user_id=u.id WHERE u.status='active' AND u.deleted_at IS NULL AND u.show_org_chart=1 ORDER BY u.org_order,u.name").all<Record<string,string>>()]);const announcements=await Promise.all(announcementRows.results.map(async row=>({...row,imageDataUrl:await imageDataUrl(row.imageKey)})));const leaders=await Promise.all(people.results.map(async person=>({...person,position:person.orgPosition||person.position,imageDataUrl:await imageDataUrl(person.avatarKey)})));return Response.json({settings:Object.fromEntries(settings.results.map(row=>[row.setting_key,row.setting_value])),announcements,events:events.results,leaders});}catch(error){console.error("Portal content read",error);return Response.json({error:"Kandungan portal tidak dapat dibaca."},{status:500});}}

export async function POST(request:Request){try{await prepare();const me=await admin(request);if(!me)return Response.json({error:"Akses pentadbir diperlukan."},{status:403});const body=await request.json() as ContentBody,now=new Date().toISOString(),id=crypto.randomUUID(),title=clean(body.title,180);if(!title)return Response.json({error:"Tajuk perlu diisi."},{status:400});if(body.kind==="announcement"){const start=clean(body.publishedAt,10)||now.slice(0,10),end=clean(body.endsAt,10)||start;if(end<start)return Response.json({error:"Tarikh tamat mesti selepas tarikh mula."},{status:400});let imageKey="";if(body.imageBase64){const mime=clean(body.imageMimeType,40);if(!["image/jpeg","image/png","image/webp"].includes(mime))return Response.json({error:"Gambar pengumuman mesti JPG, PNG atau WebP."},{status:400});const bytes=Uint8Array.from(atob(body.imageBase64),char=>char.charCodeAt(0));if(bytes.byteLength>2_000_000)return Response.json({error:"Gambar pengumuman mesti 2 MB atau kurang."},{status:400});const ext=mime==="image/png"?"png":mime==="image/webp"?"webp":"jpg";imageKey=`announcements/${id}.${ext}`;await env.FILES.put(imageKey,bytes,{httpMetadata:{contentType:mime}});}await env.DB.prepare("INSERT INTO portal_announcements(id,title,body,audience,published_at,ends_at,image_key,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'published',?,?,?)").bind(id,title,clean(body.body,2500),clean(body.audience,50)||"Semua",start,end,imageKey,me.email,now,now).run();}else{const date=clean(body.eventDate,10);if(!date)return Response.json({error:"Tarikh aktiviti perlu diisi."},{status:400});await env.DB.prepare("INSERT INTO portal_calendar(id,title,event_date,end_date,category,details,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(id,title,date,clean(body.endDate,10)||date,clean(body.category,60)||"Sekolah",clean(body.details,1200),me.email,now,now).run();}await log(me.email,`${body.kind}_create`,title);return Response.json({success:true,id});}catch(error){console.error("Portal content create",error);return Response.json({error:"Kandungan tidak dapat disimpan."},{status:500});}}

export async function DELETE(request:Request){try{await prepare();const me=await admin(request);if(!me)return Response.json({error:"Akses pentadbir diperlukan."},{status:403});const url=new URL(request.url),id=clean(url.searchParams.get("id"),80),kind=url.searchParams.get("kind");if(kind==="announcement"){const row=await env.DB.prepare("SELECT image_key AS imageKey FROM portal_announcements WHERE id=?").bind(id).first<{imageKey:string}>();if(row?.imageKey)await env.FILES.delete(row.imageKey);await env.DB.prepare("DELETE FROM portal_announcements WHERE id=?").bind(id).run();}else await env.DB.prepare("DELETE FROM portal_calendar WHERE id=?").bind(id).run();await log(me.email,`${kind}_delete`,id);return Response.json({success:true});}catch(error){console.error("Portal content delete",error);return Response.json({error:"Kandungan tidak dapat dipadam."},{status:500});}}

export async function PUT(request:Request){try{await prepare();const me=await admin(request);if(!me)return Response.json({error:"Akses pentadbir diperlukan."},{status:403});const body=await request.json() as {settings?:Record<string,string>},allowed=new Set(["school_name","school_code","school_grade","school_type","school_founded","school_motto","school_vision","school_mission","school_history","school_email","school_phone","school_address","parent_coop_url","parent_pibg_url","footer_notice"]),entries=Object.entries(body.settings||{}).filter(([key])=>allowed.has(key)),now=new Date().toISOString();if(entries.length)await env.DB.batch(entries.map(([key,value])=>env.DB.prepare("INSERT INTO portal_settings(setting_key,setting_value,updated_at) VALUES(?,?,?) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value,updated_at=excluded.updated_at").bind(key,clean(value,2500),now)));await log(me.email,"school_profile_update",entries.map(([key])=>key).join(","));return Response.json({success:true});}catch(error){console.error("Portal profile update",error);return Response.json({error:"Profil sekolah tidak dapat disimpan."},{status:500});}}
