import {matchDocumentRows} from '../../lib/document-name-matching';
import {env} from 'cloudflare:workers';
import {portalActor} from '../../server-auth';
import {documentNameKey} from '../../staff-work-model';
import {normalizeDocumentName,nameSimilarity} from '../../name-matching';
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store'}});
async function actorFor(request:Request){const actor=await portalActor(request);return actor&&['admin','super_admin'].includes(actor.role)?actor:null;}
export async function GET(request:Request){if(!await actorFor(request))return reply({error:'Akses admin diperlukan.'},403);const directory=(await env.DB.prepare("SELECT id,name FROM portal_users WHERE status='active' AND deleted_at IS NULL ORDER BY name").all<{id:string;name:string}>()).results;const drafts=await env.DB.prepare('SELECT assignments_json FROM staff_work_documents WHERE published=0').all<{assignments_json:string}>();const names=new Map<string,{name:string}>();for(const draft of drafts.results){try{for(const row of JSON.parse(draft.assignments_json)){if(typeof row.name==='string')names.set(normalizeDocumentName(row.name),{name:row.name});}}catch{}}const review=(await matchDocumentRows([...names.values()],directory)).filter(row=>!row.userId&&row.match_type!=='Confirmed No Match');const mappings=await env.DB.prepare('SELECT * FROM name_match_mappings ORDER BY updated_at DESC').all();const settings=await env.DB.prepare("SELECT high,review,margin FROM name_match_settings WHERE id='default'").first();return reply({mappings:mappings.results,settings,review});}
export async function POST(request:Request){const actor=await actorFor(request);if(!actor)return reply({error:'Akses admin diperlukan.'},403);try{
 const body=await request.json() as {action?:string;name?:string;userId?:string;high?:number;review?:number;margin?:number};
 if(body.action==='settings'){const {high,review,margin}=body;if(![high,review,margin].every(v=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=100)||Number(review)>Number(high))return reply({error:'Ambang mesti 0–100; ambang semakan tidak boleh melebihi ambang tinggi.'},400);await env.DB.prepare("UPDATE name_match_settings SET high=?,review=?,margin=? WHERE id='default'").bind(high,review,margin).run();return reply({ok:true});}
 if(typeof body.name!=='string'||body.name.length>200||!normalizeDocumentName(body.name))return reply({error:'Nama sumber tidak sah.'},400);
 const key=normalizeDocumentName(body.name);if(body.action==='forget'){await env.DB.batch([env.DB.prepare('DELETE FROM name_match_mappings WHERE normalized_source_name=?').bind(key),env.DB.prepare('DELETE FROM staff_name_mappings WHERE name_key=?').bind(documentNameKey(body.name))]);return reply({ok:true});}
 if(!['confirm','no_match'].includes(body.action||''))return reply({error:'Tindakan tidak sah.'},400);
 const user=body.action==='confirm'&&typeof body.userId==='string'?await env.DB.prepare("SELECT id,name FROM portal_users WHERE id=? AND status='active' AND deleted_at IS NULL").bind(body.userId).first<{id:string;name:string}>():null;
 if(body.action==='confirm'&&!user)return reply({error:'Pilih pengguna aktif.'},400);
 const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO name_match_mappings(id,source_name,normalized_source_name,user_id,matched_user_name,match_type,similarity_score,confirmed_by,confirmed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(normalized_source_name) DO UPDATE SET source_name=excluded.source_name,user_id=excluded.user_id,matched_user_name=excluded.matched_user_name,match_type=excluded.match_type,similarity_score=excluded.similarity_score,confirmed_by=excluded.confirmed_by,confirmed_at=excluded.confirmed_at,updated_at=excluded.updated_at`).bind(crypto.randomUUID(),body.name,key,user?.id||null,user?.name||null,user?'confirmed':'no_match',user?nameSimilarity(body.name,user.name):null,actor.id,now,now,now).run();return reply({ok:true,userId:user?.id||'',match_type:user?'Saved Mapping':'Confirmed No Match'});
 }catch{return reply({error:'Padanan tidak dapat disimpan.'},500);}}
