import { env } from "cloudflare:workers";
import { NextRequest } from "next/server";
import { markAbsenceDeletedInSheet, upsertAbsenceToSheet } from "../../../lib/google-sheets";
import { managementDrive } from "../../../management-drive";
import { managementPath } from "../../../management-catalog";
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{"Cache-Control":"private, no-store"}}); const text=(v:unknown)=>typeof v==="string"?v.trim():"";
async function parts(c:{params:Promise<{path:string[]}>}){return (await c.params).path||[]}
const reliefFolderId="kurikulum-7";

async function archiveGeneratedReliefPdf(input:{id:string;date:unknown;day:unknown;createdBy:unknown;fileName:unknown;pdfBase64:string;now:string}){
 const year=Number(String(input.date).slice(0,4)),schoolYear=Number.isInteger(year)&&year>=2020&&year<=2100?year:new Date().getFullYear();
 const day=text(input.day).slice(0,40)||"Jadual Relief";
 const originalName=((text(input.fileName).replace(/[\\/:*?"<>|]/g,"-").slice(0,180)||"Jadual-Relief-"+input.date+".pdf").replace(/\.pdf$/i,""))+".pdf";
 const title=("Jadual Relief — "+day+" "+text(input.date).slice(0,10)).slice(0,180);
 const result=await managementDrive({action:"management_upload",requestId:input.id,path:[String(schoolYear),...managementPath(reliefFolderId).split(" › "),"Analisis, laporan atau keberhasilan"],name:originalName,mimeType:"application/pdf",base64:input.pdfBase64});
 if(!result.id||!result.url)throw new Error("Drive belum mengesahkan PDF relief. Cuba simpan pelan sekali lagi.");
 await env.DB.prepare("INSERT OR IGNORE INTO management_materials(id,school_year,folder_id,title,document_type,source_url,storage_key,mime_type,original_name,notes,visibility,owner_email,owner_name,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)")
  .bind(input.id,schoolYear,reliefFolderId,title,"Analisis, laporan atau keberhasilan",result.url,result.id,"application/pdf",originalName,"Jadual relief dijana oleh Sistem Relief.","staff","",text(input.createdBy).slice(0,180)||"Sistem Relief",input.now).run();
}
export async function GET(request:NextRequest,c:{params:Promise<{path:string[]}>}){const p=await parts(c),root=p[0];
 if(root==="teachers"){const x=await env.DB.prepare("SELECT id,name,category,created_at AS createdAt FROM teachers ORDER BY category,name").all();return json({teachers:x.results})}
 if(root==="absences"){const x=await env.DB.prepare("SELECT id,teacher_id AS teacherId,teacher_name AS teacherName,category,absence_date AS absenceDate,end_date AS endDate,reason,duration,start_time AS startTime,end_time AS endTime,note,relief_status AS reliefStatus,created_at AS createdAt,updated_at AS updatedAt FROM absences ORDER BY absence_date DESC,created_at DESC").all();return json({records:x.results})}
 if(root==="absence-inbox"){const x=await env.DB.prepare("SELECT id,teacher_id,teacher_name,category,absence_date,end_date,reason,duration,start_time,end_time,note,relief_status AS status,CAST(strftime('%s',created_at) AS INTEGER) AS created_at,CAST(strftime('%s',updated_at) AS INTEGER) AS updated_at FROM absences ORDER BY absence_date DESC,created_at DESC").all();return json({reports:x.results})}
 if(root==="schedules"){const x=await env.DB.prepare("SELECT * FROM relief_schedules ORDER BY created_at DESC").all();return json({versions:x.results.map((r:any)=>({id:r.id,fileName:r.file_name,sourceLabel:r.source_label,teacherCount:Number(r.teacher_count),isActive:r.is_active==="1",createdAt:r.created_at,teachers:JSON.parse(r.teachers_json)}))})}
 if(root==="settings"){const r=await env.DB.prepare("SELECT payload_json FROM relief_settings WHERE id='active'").first<{payload_json:string}>();return json(r?JSON.parse(r.payload_json):{params:{maxRelief:2,maxLoad:7,consecutiveLimit:2,historyWeight:0,dayWeight:4},excludedNames:[],excludedClasses:[]})}
 if(root==="relief-plans"&&p[2]==="pdf"){const f=await env.FILES.get(`relief-pdfs/${p[1]}.pdf`);return f?new Response(f.body,{headers:{"Content-Type":"application/pdf","Content-Disposition":`inline; filename="${p[1]}.pdf"`}}):json({error:"PDF tidak ditemui"},404)}
 if(root==="relief-plans"){const x=await env.DB.prepare("SELECT * FROM relief_plans ORDER BY date DESC,created_at DESC").all();return json({plans:x.results.map((r:any)=>({id:r.id,date:r.date,day:r.day,createdBy:r.created_by,assignments:JSON.parse(r.assignments_json),fileName:r.file_name,createdAt:r.created_at,pdfUrl:`/api/relief-legacy/relief-plans/${r.id}/pdf`}))})}
 return json({error:"Laluan tidak ditemui"},404)}
export async function POST(request:NextRequest,c:{params:Promise<{path:string[]}>}){const p=await parts(c),root=p[0];
 if(root==="access"&&p[1]==="verify")return new Response(null,{status:request.headers.get("x-access-pin")===env.RELIEF_ACCESS_PIN?204:401});
 if(root==="admin"&&p[1]==="verify")return new Response(null,{status:request.headers.get("x-admin-pin")===env.RELIEF_ADMIN_PIN?204:401});
 const b=await request.json() as Record<string,any>,now=new Date().toISOString();
 if(root==="absences"){const id=text(b.id)||crypto.randomUUID(),record={id,teacherId:text(b.teacherId),teacherName:text(b.teacherName),category:text(b.category),absenceDate:text(b.absenceDate),endDate:text(b.endDate)||null,reason:text(b.reason),duration:text(b.duration),startTime:text(b.startTime)||null,endTime:text(b.endTime)||null,note:text(b.note),reliefStatus:"pending",createdAt:now,updatedAt:now};await env.DB.prepare("INSERT INTO absences (id,teacher_id,teacher_name,category,absence_date,end_date,reason,duration,start_time,end_time,note,relief_status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,record.teacherId,record.teacherName,record.category,record.absenceDate,record.endDate,record.reason,record.duration,record.startTime,record.endTime,record.note,"pending",now,now).run();const sheetMirrored=await upsertAbsenceToSheet(record);return json({id,status:"pending",sheetMirrored})}
 if(root==="teachers"){const id=text(b.id)||crypto.randomUUID();await env.DB.prepare("INSERT INTO teachers (id,name,category,created_at) VALUES (?,?,?,?)").bind(id,b.name,b.category,now).run();return json({id})}
 if(root==="schedules"){await env.DB.prepare("UPDATE relief_schedules SET is_active='0'").run();const id=crypto.randomUUID(),teachers=Array.isArray(b.teachers)?b.teachers:[];await env.DB.prepare("INSERT INTO relief_schedules (id,file_name,source_label,teacher_count,is_active,teachers_json,created_at) VALUES (?,?,?,?,?,?,?)").bind(id,b.fileName,b.sourceLabel||b.fileName,String(teachers.length),"1",JSON.stringify(teachers),now).run();return json({id})}
 if(root==="settings"){const payload={params:b.params||{},excludedNames:b.excludedNames||[],excludedClasses:b.excludedClasses||[]};await env.DB.prepare("INSERT INTO relief_settings (id,payload_json,updated_at) VALUES ('active',?,?) ON CONFLICT(id) DO UPDATE SET payload_json=excluded.payload_json,updated_at=excluded.updated_at").bind(JSON.stringify(payload),now).run();return json({ok:true})}
if(root==="relief-plans"){const id=crypto.randomUUID(),pdf=text(b.pdfBase64);if(pdf){await archiveGeneratedReliefPdf({id,date:b.date,day:b.day,createdBy:b.createdBy,fileName:b.fileName,pdfBase64:pdf,now});await env.FILES.put(`relief-pdfs/${id}.pdf`,Uint8Array.from(atob(pdf),x=>x.charCodeAt(0)),{httpMetadata:{contentType:"application/pdf"}})}await env.DB.prepare("INSERT INTO relief_plans (id,date,day,created_by,assignments_json,file_name,created_at) VALUES (?,?,?,?,?,?,?)").bind(id,b.date,b.day,b.createdBy,JSON.stringify(b.assignments||[]),b.fileName||`${id}.pdf`,now).run();return json({plan:{id,date:b.date,day:b.day,createdBy:b.createdBy,assignments:b.assignments||[],fileName:b.fileName,createdAt:now,pdfUrl:`/api/relief-legacy/relief-plans/${id}/pdf`}})}
 return json({error:"Laluan tidak ditemui"},404)}
export async function PUT(r:NextRequest,c:{params:Promise<{path:string[]}>}){return POST(r,c)}
export async function DELETE(request:NextRequest,c:{params:Promise<{path:string[]}>}){const p=await parts(c),root=p[0],id=p[1]||request.nextUrl.searchParams.get("id");if(root==="absences"&&request.headers.get("x-delete-password")!==env.RELIEF_DELETE_PASSWORD)return json({error:"Kata laluan tidak betul"},401);if(root==="teachers"&&request.headers.get("x-admin-pin")!==env.RELIEF_ADMIN_PIN)return json({error:"PIN tidak betul"},401);if(!id)return json({error:"ID diperlukan"},400);let sheetMirrored=true;if(root==="absences"){await env.DB.prepare("DELETE FROM absences WHERE id=?").bind(id).run();sheetMirrored=await markAbsenceDeletedInSheet(id);}else if(root==="teachers")await env.DB.prepare("DELETE FROM teachers WHERE id=?").bind(id).run();else if(root==="schedules")await env.DB.prepare("DELETE FROM relief_schedules WHERE id=?").bind(id).run();else return json({error:"Laluan tidak ditemui"},404);return json({ok:true,sheetMirrored})}
